### PR TITLE
Mark `--add-noqa` as incompatible with `--fix`

### LINKED ISSUE #2187: `--add-noqa` is unintuitive
I would expect `--add-noqa` to only add the directive to violations that ruff cannot fix but it in fact adds it everywhere.

Even worse the following just ignores the `--fix` option and does not fix anything but adds `noqa` everywhere:

```
ruff foo.py --add-noqa --fix
```

I think at least the former should be clearly explained in the option description in `--help` and the latter should result in an error until that is supported.

### PR DESCRIPTION
**Pull request by charliermarsh**
Closes #2187.

### CODE REVIEW

File: src/noqa.rs [hunk 1]
```diff
@@ -196,7 +196,6 @@ fn add_noqa_inner(
                         output.push_str(line_ending);
                     }
                     Directive::Codes(_, start_byte, _, existing) => {
-                        println!("existing: {:?}", existing);
```
Comment (charliermarsh) [inline src/noqa.rs:199]: I don't wanna talk about it.

File: ruff_cli/src/main.rs [hunk 2]
```diff
@@ -160,9 +160,12 @@ fn check(args: CheckArgs, log_level: LogLevel) -> Result<ExitCode> {
     }
 
     if cli.add_noqa {
+        if !matches!(autofix, fix::FixMode::None) {
```
Comment (charliermarsh) [inline ruff_cli/src/main.rs:163]: This is a rare path, since you can't set `--fix` on the CLI with `--add-noqa`. But if the user's `pyproject.toml` has `fix = true`, we warn.
