### PR TITLE
Fix SIM222 and SIM223 false positives and auto-fix

### LINKED ISSUE #4058: SIM222 False positive
Related to https://github.com/MartinThoma/flake8-simplify/issues/142 ?
Similar to #3830

```
something = 'foo' or True
```
```
$ ruff --show-source sim222.py 
sim222.py:1:13: SIM222 [*] Use `True` instead of `... or True`
  |
1 | something = 'foo' or True
  |             ^^^^^^^^^^^^^ SIM222
  |
  = help: Replace with `True`
```

### PR DESCRIPTION
**Pull request by JonathanPlasse**
- Close #4058

Special case truthy expressions like side-effect expressions.
If a truthy expression is followed by the short-circuiting boolean, remove the short-circuiting boolean too as it is unnecessary.
The violation message should be changed in this case to something like "remove everything after the truth expression".
```python
assert ("foo" and False) == "foo"
assert ("foo" or True) == "foo"
```

I use `Truthiness` from `flake8-bandit`, but `flake8-pytest` also has `is_falsy_constant()`.
Should we make extract `Truthiness` from `flake8-bandit`, add the missing cases from `flake8-pytest`, and use it for `flake8-bandit`, `flake8-pytest`, and `flake8-simplify`?
I would be open making another PR for this.

### CODE REVIEW

**Comment by charliermarsh** [comment]
Yeah, I'd vote to extract that concept into `ruff_python_semantic` and use it in more places!

File: crates/ruff/src/rules/flake8_simplify/rules/ast_bool_op.rs [hunk 1]
```diff
@@ -503,30 +504,53 @@ pub fn expr_or_not_expr(checker: &mut Checker, expr: &Expr) {
...
     if op != expected_op {
         return None;
     }
-    let short_circuit_value = match op {
-        Boolop::And => false,
-        Boolop::Or => true,
+    let (short_circuit_value, short_circuit_string) = match op {
+        Boolop::And => (false, "False".to_string()),
+        Boolop::Or => (true, "True".to_string()),
     };
```
Comment (MichaReiser) [inline crates/ruff/src/rules/flake8_simplify/rules/ast_bool_op.rs:529]: Nit: Can we move the `to_string` call to where we create the `Edit` to avoid allocating a string on the heap if there are no diagnostics.

**Review by MichaReiser — APPROVED** [review]

File: crates/ruff/src/rules/flake8_bandit/rules/shell_injection.rs [hunk 2]
```diff
@@ -173,6 +173,16 @@ impl From<&Keyword> for Truthiness {
...
+            ExprKind::Constant {
+                value: Constant::Str(str),
+                ..
+            } => {
+                if str.is_empty() {
+                    Truthiness::Falsey
+                } else {
+                    Truthiness::Truthy
+                }
+            }
```
Comment (charliermarsh) [inline crates/ruff/src/rules/flake8_bandit/rules/shell_injection.rs:185]: I guess we should also include `JoinedStr` here, and maybe the `ITERABLE_INITIALIZERS` logic we see in `flake8-pytest`? Whatever's most comprehensive.

File: crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM222_SIM222.py.snap [hunk 3]
```diff
@@ -116,4 +116,242 @@ SIM222.py:30:4: SIM222 [*] Use `True` instead of `... or True`
...
+47 47 | if a or "" or True:  # SIM222
+48 48 |     pass
+49 49 | 
+50    |-if a or "foo" or True or "bar":  # SIM222
+   50 |+if a or "foo":  # SIM222
+51 51 |     pass
+52 52 | 
+53 53 | if a or 0 or True:  # SIM222
+
+SIM222.py:53:4: SIM222 [*] Use `True` instead of `... or True`
```
Comment (charliermarsh) [inline crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM222_SIM222.py.snap:157]: Can we update these diagnostic messages, since they no longer reflect the suggestion IIUC?

File: crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM223_SIM223.py.snap [hunk 4]
```diff
@@ -116,4 +116,242 @@ SIM223.py:25:4: SIM223 [*] Use `False` instead of `... and False`
...
+48 |     pass
+   |
+   = help: Replace with `False`
+
+ℹ Suggested fix
+42 42 | if a and "" and False:  # SIM223
+43 43 |     pass
+44 44 | 
+45    |-if a and "foo" and False and "bar":  # SIM223
+   45 |+if a and "foo":  # SIM223
```
Comment (charliermarsh) [inline crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM223_SIM223.py.snap:152]: So in the summary, we mention:

```py
assert ("foo" and False) == "foo"
```

But I don't _think_ this holds, since the left-hand side evaluates to `False`. And in this example here, `a and "foo"` isn't equivalent to `a and "foo" and False and "bar"`, is it?

Comment (JonathanPlasse) [reply crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM223_SIM223.py.snap:152]: You are right it should check for falsey value not truthy value for `and` operands.
```python
assert ("" and False) == ""
```

File: crates/ruff/src/rules/flake8_bandit/rules/shell_injection.rs (hunk 2 above)
Comment (JonathanPlasse) [reply crates/ruff/src/rules/flake8_bandit/rules/shell_injection.rs]: Done.

File: crates/ruff/src/rules/flake8_simplify/rules/ast_bool_op.rs [hunk 5]
```diff
@@ -503,26 +504,28 @@ pub fn expr_or_not_expr(checker: &mut Checker, expr: &Expr) {
...
     for (value, next_value) in values.iter().tuple_windows() {
-        // Keep track of the location of the furthest-right, non-effectful expression.
-        if contains_effect(value, |id| ctx.is_builtin(id)) {
+        // Keep track of the location of the furthest-right, truthy or falsey expression
+        let value_truthiness = Truthiness::from_expr(value, |id| checker.ctx.is_builtin(id));
+        let next_value_truthiness =
+            Truthiness::from_expr(next_value, |id| checker.ctx.is_builtin(id));
+
+        // Keep track of the location of the furthest-right, non-effectful expression
+        if value_truthiness.is_unknown() && contains_effect(value, |id| checker.ctx.is_builtin(id))
```
Comment (JonathanPlasse) [inline crates/ruff/src/rules/flake8_simplify/rules/ast_bool_op.rs:527]:
```python
a and ""
a or "a"
```
is replaced by
```python
""
"a"
```
This auto-fix would only work if the result of the boolean operations inside `bool(...)` or `if ...`.

We should only check for truthiness is unknown and not `contains_effect` in the other cases.

File: crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM222_SIM222.py.snap (hunk 3 above)
Comment (JonathanPlasse) [reply crates/ruff/src/rules/flake8_simplify/snapshots/ruff__rules__flake8_simplify__tests__SIM222_SIM222.py.snap:157]: Done!

File: crates/ruff/src/rules/flake8_simplify/rules/ast_bool_op.rs (hunk 5 above)
Comment (JonathanPlasse) [reply crates/ruff/src/rules/flake8_simplify/rules/ast_bool_op.rs:540]: I am working on a visitor to know if we are in a boolean context (i.e. boolean operation result will be converted to a boolean).

**Comment by JonathanPlasse** [comment]
I added `in_test` to `Context`.
It is considered to be in a test context when you are inside an `if` or an `assert` test, or inside the builtin `bool`.
Boolean operations inside other expressions than boolean operations are not in a test context.

For example:
```python
# Inside test `a` is simplified

bool(a or [1] or True or [2])

assert a or [1] or True or [2]

if (a or [1] or True or [2]) and (a or [1] or True or [2]):
    pass

# Outside test `a` is not simplified

a or [1] or True or [2]

if (a or [1] or True or [2]) == (a or [1]):
    pass

if f(a or [1] or True or [2]):
    pass
```

**Comment by JonathanPlasse** [comment]
There is a false positive that has been fixed in `airflow`.
```python
self.max_messages = max_messages or True
```

**Comment by JonathanPlasse** [comment]
Should I split this PR?

**Comment by charliermarsh** [comment]
I think it would be helpful. What do you think we can carve out into separate PRs?

**Comment by JonathanPlasse** [comment]
Here is the list of possible PRs
1. Extract `Truthiness`
2. Add `in_test` to `Context`
3. Fix `SIM222` and `SIM223` false positives and auto-fix (this PR)

**Comment by JonathanPlasse** [comment]
The rebase is done.
It is ready for review.

**Comment by JonathanPlasse** [comment]
I will document the rules as we diverge a lot from the behavior of `flake8-simplify`.

**Comment by JonathanPlasse** [comment]
I documented the rules and detect when `... or True`, `True or ...`, or `... or True or ...` is used and adapted the violation message.
