### PR TITLE
Avoid `RUF007` fixes for more than two arguments

### LINKED ISSUE #3651: RUF007 - False positive when `zip()` contains more than 2 arguments
RUF007 should only hit when `zip()` is called with no more than 2 arguments, as `pairwise()` does not support it. 

Introduced with #3501 

See
- https://docs.python.org/3/library/itertools.html#itertools.pairwise
- https://docs.python.org/3/library/functions.html#zip

`pyproject.toml`
```toml
[tool.ruff]
target-version = "py311"
``` 

`test.py`
```python
foo = [1, 2, 3, 4]

bar = zip(foo[:-1], foo[1:], foo, strict=True)
```

`ruff test.py`
```ruby
test.py:5:7: RUF007 Prefer `itertools.pairwise()` over `zip()` when iterating over successive pairs
Found 1 error.
```

`ruff --version`
```bash
ruff 0.0.257
```

### PR DESCRIPTION
**Pull request by JonathanPlasse**
- Close #3651

### CODE REVIEW

File: crates/ruff/src/rules/ruff/rules/pairwise_over_zipped.rs [hunk 1]
```diff
@@ -93,7 +93,7 @@ pub fn pairwise_over_zipped(checker: &mut Checker, func: &Expr, args: &[Expr]) {
         return;
     };
 
-    if !(args.len() > 1 && id == "zip" && checker.ctx.is_builtin(id)) {
+    if !(args.len() == 2 && id == "zip" && checker.ctx.is_builtin(id)) {
```
Comment (charliermarsh) [inline crates/ruff/src/rules/ruff/rules/pairwise_over_zipped.rs:96]: I think we may want to avoid _both_ `args != 2` _and_ `strict=True`, since the latter isn't supported?

Comment (charliermarsh) [reply crates/ruff/src/rules/ruff/rules/pairwise_over_zipped.rs:96]: I think this current approach only catches extra arguments, but not the unsupported kwargs.

Comment (JonathanPlasse) [reply crates/ruff/src/rules/ruff/rules/pairwise_over_zipped.rs]: Done.

Comment (aberres) [reply crates/ruff/src/rules/ruff/rules/pairwise_over_zipped.rs]: @charliermarsh  But isn't this a valid case for pairwise `zip(foo[:-1], foo[1:], strict=True)`?

Comment (JonathanPlasse) [reply crates/ruff/src/rules/ruff/rules/pairwise_over_zipped.rs]: Indeed

Comment (charliermarsh) [reply crates/ruff/src/rules/ruff/rules/pairwise_over_zipped.rs]: Oh hmm, in that case, isn't _either_ `strict` argument acceptable? (`False` is of course fine.)
