### PR TITLE
Automatically linkify option references in rule documentation

### LINKED ISSUE #2766: Link relevant settings in rule documentation
The individual rule documentation pages should reflect which settings are available that impact that rule. We could rely on the developers updating the documentation description with new rules and settings, but this is error prone. 

A dedicated section could help structure the related rules (did not find a good example in pylint etc.)

A more engineering heavy option is to keep track of a mapping between rules and options. (cc: @not-my-profile) This approach allows for automatic link generation, and linking from rule -> setting and vice versa.

Example:
- For [relative imports](https://beta.ruff.rs/docs/rules/relative-imports/) (link to strictness option seems broken, should be [this](https://github.com/charliermarsh/ruff#ban-relative-imports))
- For [unconventional-import-alias](https://beta.ruff.rs/docs/rules/unconventional-import-alias/), we have not linked the [relevant settings](https://beta.ruff.rs/docs/settings/#flake8-import-conventions) yet.

No strong preference, just putting the idea on the table.

### PR DESCRIPTION
**Pull request by not-my-profile**
Previously the rule documentation referenced configuration options
via full https:// URLs, which was bad for several reasons:

* changing the website would mean you'd have to change all URLs
* the links didn't work when building mkdocs locally
* the URLs showed up in the `ruff rule` output
* broken references weren't detected by our CI

This commit solves all of these problems by post-processing the
Markdown, recognizing sections such as:

    ## Options

    * `flake8-tidy-imports.ban-relative-imports`

`cargo dev generate-all` will automatically linkify such references
and panic if the referenced option doesn't exist.
Note that the option can also be linked in the other Markdown sections
via e.g. [`flake8-tidy-imports.ban-relative-imports`] since
the post-processing code generates a CommonMark link definition.

Resolves #2766.

### CODE REVIEW

File: crates/ruff_dev/src/generate_docs.rs [hunk 1]
```diff
@@ -49,3 +49,32 @@ pub fn main(args: &Args) -> Result<()> {
...
+            in_options = line == "## Options\n";
+        } else if in_options {
+            if let Some(rest) = line.strip_prefix("* `") {
+                // TODO(martin): Assert that the option actually exists
+
+                let option = rest.trim_end().trim_end_matches('`');
+                let anchor = option.rsplit('.').next().unwrap();
+                out.push_str(&format!("* [`{option}`]\n"));
+                after.push_str(&format!(
+                    "[`{option}`]: https://github.com/charliermarsh/ruff#{anchor}"
```
Comment (sbrugman) [inline crates/ruff_dev/src/generate_docs.rs:68]: Nit: Can we link to the docs?

**Comment by sbrugman** [comment]
Elegant solution, love it

File: crates/ruff_dev/src/generate_docs.rs (hunk 1 above)
Comment (not-my-profile) [reply crates/ruff_dev/src/generate_docs.rs]: Sure :) Changed it to `../../settings#{anchor}` ... which *should* work ... I am not certain since I don't know how to build mkdocs locally, see #2802.

File: docs/rules/unused-variable.md [hunk 2]
```diff
@@ -28,4 +32,6 @@ Use instead:
 def foo():
     x = 1
     return x
-```
\ No newline at end of file
+```
+
+[`dummy-variable-rgx`]: ../../settings#dummy-variable-rgx
```
Comment (charliermarsh) [inline docs/rules/unused-variable.md:37]: Should this be an absolute link to GitHub? What happens when the user runs `ruff rule ...`? Do we show the relative link?

Comment (not-my-profile) [reply docs/rules/unused-variable.md:37]: I initially linked these to the GitHub README but @sbrugman suggested to instead link the mkdocs page ... which I think makes sense, since it's weird if https://beta.ruff.rs/docs/ suddenly links you to the GitHub README.

I guess the only problem is that if you now follow these links in the GitHub README these links are broken ... which could be fixed by having absolute links to https://beta.ruff.rs/docs/settings/ ... but I think it would actually be better to stop listing the rules and configuration options in the README and have them solely on the documentation website. I'd also remove the `docs/rules/*.md` files from the master branch and only generate them for `mkdocs` ... having to run `cargo dev generate-all` all the time is annoying ... but it's your call ... I can also just change it to an absolute ruff.rs URL for now.

> What happens when the user runs ruff rule ...? Do we show the relative link?

This isn't part of the `ruff rule` output at all ... since it's only added by generate-docs for the `.md` files.

Comment (charliermarsh) [reply docs/rules/unused-variable.md:37]: Ah right, this makes sense. Even if we leave the rules and configuration options in the README, we could just remove the checked-in versions and have the README links point to the versions in the docs?

Comment (charliermarsh) [reply docs/rules/unused-variable.md:37]: We can follow-up though if we want to do that -- this makes sense for now.
