### PR TITLE
Remove empty line after RUF100 auto-fix

### LINKED ISSUE #2845: RUF100 may leave an empty line behind
ruff 0.0.246

When an unused `noqa` is alone on a line, the autofix leaves an empty line behind in its place.

```shellsession
$ cat t.py
# noqa: FOO42
print("hello")
$ ruff --select RUF --fix t.py
Found 1 error (1 fixed, 0 remaining).
$ cat t.py

print("hello")
```

I suppose it would be better to remove the empty line. (Black likely does that when run after ruff on the file.)

### LINKED ISSUE #3413: RUF100 auto-fix remove comments
```python
# noqa # first comment
# noqa: E501 # second comment
```
The comments after the `noqa`s are removed after the auto-fix.

### PR DESCRIPTION
**Pull request by JonathanPlasse**
- Closes #2845
- Comments after `noqa`s are removed after the auto-fix, this is not a regression. It was already the case.
I opened an issue to track it #3413.

Edit:

- Closes #3413

### CODE REVIEW

File: crates/ruff/src/noqa.rs [hunk 1]
```diff
@@ -20,7 +20,7 @@ use crate::rule_redirects::get_redirect_target;
 
 static NOQA_LINE_REGEX: Lazy<Regex> = Lazy::new(|| {
     Regex::new(
-        r"(?P<spaces>\s*)(?P<noqa>(?i:# noqa)(?::\s?(?P<codes>([A-Z]+[0-9]+(?:[,\s]+)?)+))?)",
+        r"(?P<spaces>\s*)(?P<noqa>(?i:# noqa)(?::\s?(?P<codes>(?:[A-Z]+[0-9]+)(?:[,\s]+[A-Z]+[0-9]+)*))?)(?P<spaces_after_noqa>\s*)",
```
Comment (JonathanPlasse) [inline crates/ruff/src/noqa.rs:23]: `spaces_after_noqa` is used to conserve spaces when there is
```python
print(a)  # noqa: E501, F821 # comment
```
which would become this without matching for `spaces_after_noqa`.
```python
print(a)  # noqa: F821# comment
```
Instead of this
```python
print(a)  # noqa: F821 # comment
```
It is also used to have a better error range.

**Comment by charliermarsh** [comment]
Nice! Thank you.
