### PR TITLE
Fix infinite loop due to rules `D207` & `W605`

### LINKED ISSUE #3522: [Infinite Loop] Failed to converge after 100 iterations.
Ruff 0.0.255
Command
```
ruff ~/Desktop/Ruff/Broken/AcquireFile6.py --config /home/rafal/Desktop/ruff.toml --fix --no-cache
```
Settings
```
select = ["ALL"]
```

[AcquireFile6.py.zip](https://github.com/charliermarsh/ruff/files/10973446/AcquireFile6.py.zip)

produce error 
```
error: Failed to converge after 100 iterations.

This indicates a bug in `ruff`. If you could open an issue at:

    https://github.com/charliermarsh/ruff/issues/new?title=%5BInfinite%20loop%5D

...quoting the contents of `AcquireFile6.py`, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

```

### PR DESCRIPTION
**Pull request by vlindhol**
Closes #3522

 ### Issue addressed

Given the following example case:

```python
class A:
    """
\ a
    """
```

With the config:

```toml
select = [
  "D207", # bad docstring indentation
  "W605", # invalid escape sequence
]
```

Those two rules clash when autofixing, creating an infinite loop:

1. `W605` schedules an insertion of a `\` at column 0
2. `D207` schedules an insertion of `....` (four spaces) at column 0
3. End result: `\ a` -> `\` + `    ` + `\ a` -> `\    \ a`
4. GOTO 1

 ### Solution

The culprit is the fairly simplistic way that "fix overlaps" are calculated.

1. Firstly, add an explicit ordering of the rules so that they are applied
   in an order that doesn't break the intent (i.e. FIRST indent, THEN fix
   the escape sequence.
2. For future, similar clashes: make `W605` insert the second `\` AFTER the
   first one, rather than BEFORE. This marks one more character in the code
   as "dirty", postponing other fixes in that same column for the next
   autofix iteration.

 ### Test plan

- [ ] ~~Add a new test covering this pathological case. (TODO: how?)~~
- [x] Test manually that the above example now gets fixed correctly.

### CODE REVIEW

**Comment by vlindhol** [comment]
I would like to add a test that tests the interplay between these two rules, but not sure where to put it?

File: crates/ruff/src/rules/pycodestyle/rules/invalid_escape_sequence.rs [hunk 1]
```diff
@@ -114,7 +114,10 @@ pub fn invalid_escape_sequence(
                     Range::new(location, end_location),
                 );
                 if autofix {
-                    diagnostic.amend(Fix::insertion(r"\".to_string(), location));
+                    diagnostic.amend(Fix::insertion(
+                        r"\".to_string(),
+                        Location::new(location.row(), location.column() + 1),
```
Comment (charliermarsh) [inline crates/ruff/src/rules/pycodestyle/rules/invalid_escape_sequence.rs:119]: It might _also_ be possible to fix this by giving one rule precedence in `crates/ruff/src/autofix/mod.rs#cmp_fix`, so that we apply the fixes in a specific order even when they're anchored to the same code point. But, what you have here is good too, arguably better.

**Comment by charliermarsh** [comment]
> I would like to add a test that tests the interplay between these two rules, but not sure where to put it?

Hmm, yeah, there's not a natural place for this since it cuts across categories. But, the best I can think of is a dedicated test in `crates/ruff/src/rules/ruff/mod.rs`!

File: crates/ruff/src/rules/pycodestyle/rules/invalid_escape_sequence.rs (hunk 1 above)
Comment (vlindhol) [reply crates/ruff/src/rules/pycodestyle/rules/invalid_escape_sequence.rs:119]: Good callout! `cmp_fix` wasn't there when I forked the repo, I'll make a change there as well. Think I'll still keep my "insert at column 1" change, might help with other rules clashing in a similar way.

I was thinking of how to make the overlap logic more robust, but didn't come up with anything yet. Need to get the hang of the codebase a bit more I think :)

**Comment by vlindhol** [comment]
> Hmm, yeah, there's not a natural place for this since it cuts across categories. But, the best I can think of is a dedicated test in `crates/ruff/src/rules/ruff/mod.rs`!

I gave it a shot, but couldn't quite think of an elegant way of testing it without pulling in half the world or reimplementing the rules in the test, which kinda defeats the purpose. My Rust skills are not great, I'm contributing to get better though :)

Anyway, gave up on the test for now! My intuition says that for nice testability it should be easier to compose the rules, but e.g. the `indent` rule takes the entire `Checker` object as a param, and checks if the rules are enabled from within the rule body. Itching to refactor that, but then again I'm not confident enough in the codebase to do that, and maybe it kills performance as well?

**Comment by vlindhol** [comment]
Not super stoked about the performance hit either... I'm guessing it's the added `match` case in the rule sorting?

File: crates/ruff/src/autofix/mod.rs [hunk 2]
```diff
@@ -100,6 +100,9 @@ fn cmp_fix(rule1: Rule, rule2: Rule, fix1: &Fix, fix2: &Fix) -> std::cmp::Orderi
             // Apply `EndsInPeriod` fixes before `NewLineAfterLastParagraph` fixes.
             (Rule::EndsInPeriod, Rule::NewLineAfterLastParagraph) => std::cmp::Ordering::Less,
             (Rule::NewLineAfterLastParagraph, Rule::EndsInPeriod) => std::cmp::Ordering::Greater,
+            // Apply `UnderIndentation` fixes before `InvalidEscapeSequence` fixes.
+            (Rule::UnderIndentation, Rule::InvalidEscapeSequence) => std::cmp::Ordering::Less,
+            (Rule::InvalidEscapeSequence, Rule::UnderIndentation) => std::cmp::Ordering::Greater,
```
Comment (charliermarsh) [inline crates/ruff/src/autofix/mod.rs:105]: I think we can omit this for now if we're gonna go with the other fix. I'd like to avoid these special-cases to the degree that we can.

**Comment by charliermarsh** [comment]
Sounds good. It's possible that the performance hit is noise, I'm surprised by it.

File: crates/ruff/src/autofix/mod.rs (hunk 2 above)
Comment (vlindhol) [reply crates/ruff/src/autofix/mod.rs:105]: Will do!

**Comment by charliermarsh** [comment]
Rock on, thank you! If you're interested in more good issues let me know :)
