### PR TITLE
Fix B025 location

### LINKED ISSUE #1359: Improve B025 location
### Current

image

- B025 is raised against the try statement
- Difficult to identify duplicate locations

### Proposed

image

- B025 is raised against each duplicate
- Easy to identify duplicate locations

### PR DESCRIPTION
**Pull request by harupy**
Closes #1359 

## Before

```
   |
15 | / try:
16 | |     a = 1
17 | | except ValueError:
18 | |     a = 2
19 | | except ValueError:
20 | |     a = 2
   | |_________^ B025
   |
resources/test/fixtures/flake8_bugbear/B025.py:22:1: B025 try-except block with duplicate exception `pickle.PickleError`
   |
22 | / try:
23 | |     a = 1
24 | | except pickle.PickleError:
25 | |     a = 2
26 | | except ValueError:
27 | |     a = 2
28 | | except pickle.PickleError:
29 | |     a = 2
   | |_________^ B025
   |
resources/test/fixtures/flake8_bugbear/B025.py:31:1: B025 try-except block with duplicate exception `TypeError`
   |
31 | / try:
32 | |     a = 1
33 | | except (ValueError, TypeError):
34 | |     a = 2
35 | | except ValueError:
36 | |     a = 2
37 | | except (OSError, TypeError):
38 | |     a = 2
   | |_________^ B025
   |
resources/test/fixtures/flake8_bugbear/B025.py:31:1: B025 try-except block with duplicate exception `ValueError`
   |
31 | / try:
32 | |     a = 1
33 | | except (ValueError, TypeError):
34 | |     a = 2
35 | | except ValueError:
36 | |     a = 2
37 | | except (OSError, TypeError):
38 | |     a = 2
   | |_________^ B025
   |
Found 4 error(s).
```

## After

```
   |
19 | except ValueError:
   |        ^^^^^^^^^^ B025
   |
resources/test/fixtures/flake8_bugbear/B025.py:28:8: B025 try-except block with duplicate exception `pickle.PickleError`
   |
28 | except pickle.PickleError:
   |        ^^^^^^^^^^^^^^^^^^ B025
   |
resources/test/fixtures/flake8_bugbear/B025.py:35:8: B025 try-except block with duplicate exception `ValueError`
   |
35 | except ValueError:
   |        ^^^^^^^^^^ B025
   |
resources/test/fixtures/flake8_bugbear/B025.py:37:18: B025 try-except block with duplicate exception `TypeError`
   |
37 | except (OSError, TypeError):
   |                  ^^^^^^^^^ B025
   |
Found 4 error(s).
```

### CODE REVIEW

File: src/flake8_bugbear/plugins/duplicate_exceptions.rs [hunk 1]
```diff
@@ -34,7 +34,7 @@ fn duplicate_handler_exceptions<'a>(
             if seen.contains_key(&call_path) {
                 duplicates.insert(call_path);
             } else {
-                seen.insert(call_path, type_);
+                seen.entry(call_path).or_insert(type_);
```
Comment (charliermarsh) [inline src/flake8_bugbear/plugins/duplicate_exceptions.rs:37]: Lol I was just trying to get this to work... Seems like a false-positive with Clippy, since the autofix fails?
