### PR TITLE
Fix `RUF010` autofix within f-strings

### LINKED ISSUE #4414: [Autofix error] SyntaxError from RUF010
Applying `ruff --fix` (v0.0.267) to [this line](https://github.com/materialsproject/pymatgen/blob/8fded9b450fb1952d3d915adebff2e551d69c360/pymatgen/io/packmol.py#L217)

```py
file_contents += f"  number {str(d['number'])}\n"
```

causes

> error: Autofix introduced a syntax error. Reverting all changes.

The attempted fix is

> pymatgen/io/packmol.py:217:42: RUF010 Use conversion in f-string

Workaround is to manually change to

```py
file_contents += f"  number {d['number']!s}\n"
```

### PR DESCRIPTION
**Pull request by JonathanPlasse**
- Close #4414

### CODE REVIEW

File: crates/ruff/src/rules/ruff/rules/explicit_f_string_type_conversion.rs [hunk 1]
```diff
@@ -41,72 +46,113 @@ impl AlwaysAutofixableViolation for ExplicitFStringTypeConversion {
...
+    if checker.patch(diagnostic.kind.rule()) {
+        diagnostic.try_set_fix(|| {
+            fix_explicit_f_string_type_conversion(
+                expr,
+                &formatted_values,
+                checker.locator,
+                checker.stylist,
+            )
+        });
     }
```
Comment (charliermarsh) [inline crates/ruff/src/rules/ruff/rules/explicit_f_string_type_conversion.rs:156]: It looks like we now generate one diagnostic for the whole f-string (and that the diagnostic range is that of the entire f-string).

I think it'd be preferable to retain one diagnostic per formatted value, and limit the diagnostic to the formatted value. It's fine if the autofix contents include the whole string, even for each formatted value, but they should be separate diagnostics. (E.g., we could iterate over `formatted_values` and create one diagnostic per index, with a fix specific to that index.)

File: crates/ruff/src/rules/ruff/rules/explicit_f_string_type_conversion.rs [hunk 2]
```diff
@@ -41,72 +46,113 @@ impl AlwaysAutofixableViolation for ExplicitFStringTypeConversion {
...
-        return;
-    }
-
-    let ExprKind::Name(ast::ExprName { id, .. }) = &func.node else {
-        return;
-    };
+    Ok(Fix::automatic(Edit::range_replacement(
+        state.to_string(),
+        range,
+    )))
```
Comment (charliermarsh) [inline crates/ruff/src/rules/ruff/rules/explicit_f_string_type_conversion.rs:91]: (An alternative fix would be to just use `"foo"` directly given `str("foo")`, and then add the `!r` manually, instead of using `unparse`.) What you have here looks more robust, but the direct fix would also be safe (and is faster since we don't have to reparse the f-string). I leave it up to you!

Comment (JonathanPlasse) [reply crates/ruff/src/rules/ruff/rules/explicit_f_string_type_conversion.rs]: I just did that.

**Comment by charliermarsh** [comment]
Awesome, thank you!
