### PR TITLE
Make FLY002 autofix into a constant string instead of an f-string if all `join()` arguments are strings

### LINKED ISSUE #4769: FLY002: incorrect behavior of automatic fixer on strings
Example:
```python
print(','.join(['first', 'second']))
```

Run ruff:
```
$ ruff test-FLY002.py --select FLY --fix
Found 1 error (1 fixed, 0 remaining).
```

Fixed result:
```
print(f'first,second')
```

Expected: if the list contains only strings (no variables), you do not need to do f-string

### PR DESCRIPTION
**Pull request by evanrittenhouse**
## Summary
Fixes #4769. If all arguments to `join()` are strings, we want to autofix the code into a string instead of an f-string. For example:
```python
# OLD
', '.join('apple', 'banana', 'cherry') # currently suggests f'apple, banana, cherry'

# NEW
', '.join('apple', 'banana', 'cherry') # now suggests 'apple, banana, cherry' (no f-string)
``` 

## Test Plan
`cargo t`

### CODE REVIEW

File: crates/ruff/src/rules/flynt/rules/static_join_to_fstring.rs [hunk 1]
```diff
@@ -44,21 +46,39 @@ fn build_fstring(joiner: &str, joinees: &[Expr]) -> Option<Expr> {
...
+        }
     }
 
-    let node = ast::ExprJoinedStr {
-        values: fstring_elems,
-        range: TextRange::default(),
+    let node = if string_args.len() == joinees.len() {
+        ast::Expr::Constant(ast::ExprConstant {
+            value: Constant::Str(string_args.iter().join(joiner)),
+            range: TextRange::default(),
```
Comment (evanrittenhouse) [inline crates/ruff/src/rules/flynt/rules/static_join_to_fstring.rs:62]: `range` and `kind` are irrelevant since the autofix uses the range of the original `expr` (see the `Diagnostic`'s construction in `static_join_to_fstring`)

File: crates/ruff/src/rules/flynt/rules/static_join_to_fstring.rs [hunk 2]
```diff
@@ -44,21 +46,39 @@ fn build_fstring(joiner: &str, joinees: &[Expr]) -> Option<Expr> {
...
+            kind: None,
```
Comment (evanrittenhouse) [inline crates/ruff/src/rules/flynt/rules/static_join_to_fstring.rs:63]: `range` and `kind` are irrelevant since the autofix uses the range of the original `expr` (see the `Diagnostic`'s construction in `static_join_to_fstring`)

**Comment by evanrittenhouse** [comment]
Wonder if we should make it emit a string if all arguments are constants, not just strings. Makes sense but wasn't the exact issue

**Comment by charliermarsh** [comment]
Thank you :) Do you mind enabling edits so that I can update the branch?

**Comment by charliermarsh** [comment]
> Not sure if we want to change this to work with other types as well?

I think it's fine to skip this for now.

**Comment by evanrittenhouse** [comment]
> Thank you :) Do you mind enabling edits so that I can update the branch?
Done!

File: crates/ruff/src/rules/flynt/rules/static_join_to_fstring.rs [hunk 3]
```diff
@@ -27,15 +28,48 @@ impl AlwaysAutofixableViolation for StaticJoinToFString {
...
+                            None
+                        }
+                    })
+                    .join(joiner),
+            ),
+            range: TextRange::default(),
+            kind: None,
+        };
+        return Some(node.into());
+    }
```
Comment (charliermarsh) [inline crates/ruff/src/rules/flynt/rules/static_join_to_fstring.rs:66]: This is a little more verbose, and it returns two passes, but it avoids allocating two vectors in every case.

Comment (evanrittenhouse) [reply crates/ruff/src/rules/flynt/rules/static_join_to_fstring.rs:66]: @charliermarsh Why do we want to avoid allocations instead of 2 passes in this case?

Comment (charliermarsh) [reply crates/ruff/src/rules/flynt/rules/static_join_to_fstring.rs:66]: My intuition is that the allocations would be more expensive than iterating over the vector a second time.

Comment (evanrittenhouse) [reply crates/ruff/src/rules/flynt/rules/static_join_to_fstring.rs:66]: Gotcha, thanks - just trying to get better :)

Comment (charliermarsh) [reply crates/ruff/src/rules/flynt/rules/static_join_to_fstring.rs:66]: Of course, I appreciate it — me too :)

I’m not an expert but I generally try to consider allocations expensive. In this case, we’re already iterating over this vec, so iterating over it again should be cheap, compared to the allocations at least.
