### PR TITLE
Fix UP036 auto-fix error

### LINKED ISSUE #4522: [Autofix error] UP036 autofix fails on complex nested block
UP036 transforms the following 

```python
import sys

if sys.version_info < (3, 8):

    def a():
        if b:
            print(1)
        elif c:
            print(2)
        return None

else:
    pass
```

to 

```python
import sys

if c:
            print(2)
        return None

else:
    pass
```

which is invalid syntax and also removed ~~a lot of~~ the code incompletely.

Command:

```
ruff --no-cache --select UP036 --fix code.py 
```

ruff version fd16d658e9407ce76bc38cd8f5112dd272fc5be0

### PR DESCRIPTION
**Pull request by JonathanPlasse**
- Close #4522

## Summary

The `BlockMetadata` was incorrect. It was picking up `else` and `elif` tokens inside the `if` body.
Now, it will skip all tokens inside the `if` body.

## Test Plan

A fixture with the failing auto-fix has been added.

### CODE REVIEW

File: crates/ruff/src/rules/pyupgrade/rules/outdated_version_block.rs [hunk 1]
```diff
@@ -52,36 +52,28 @@ impl BlockMetadata {
...
 {
     indentation(locator, located)?;
 
-    let line_start = locator.line_start(located.start());
-    // Start the selection at the start-of-line. This ensures consistent indentation
-    // in the token stream, in the event that the entire block is indented.
-    let text = locator.slice(TextRange::new(line_start, located.end()));
+    let located_start = located.start();
+    let text = locator.slice(TextRange::new(located_start, located.end()));
+    let body_end = body.last().map(Ranged::end).unwrap();
```
Comment (JonathanPlasse) [inline crates/ruff/src/rules/pyupgrade/rules/outdated_version_block.rs:63]: Using `located.start()` does not seem to change the behavior.

File: crates/ruff/src/rules/pyupgrade/rules/outdated_version_block.rs [hunk 2]
```diff
@@ -52,36 +52,31 @@ impl BlockMetadata {
...
+    )
+    .flatten()
+    .filter(|(tok, _)| matches!(tok, Tok::If | Tok::Elif | Tok::Else))
     {
         if starter.is_none() {
             starter = Some(tok.clone());
+        } else if range.start() < body_end {
+            // Continue until the end of the `if` body, thus ensuring that we don't
+            // accidentally pick up an `else` or `elif` in the nested block.
+            continue;
```
Comment (charliermarsh) [inline crates/ruff/src/rules/pyupgrade/rules/outdated_version_block.rs:79]: What if there's an `else` in the `elif` block body? Would we not accidentally flag that as the final `else`?

Comment (JonathanPlasse) [reply crates/ruff/src/rules/pyupgrade/rules/outdated_version_block.rs:79]: We need `elif` or `else` or neither, We do not need both. So, I simplified the logic.
