### PR TITLE
Treat non-future function annotations as required-at-runtime

### LINKED ISSUE #4020: TCH003 false positive when typing nested functions
consider `test.py`
```
from collections.abc import Callable, Collection


def test():
    def nested() -> Callable[[Collection[str]], list[str]]:
        def double_nested(x: Collection[str]) -> list[str]:
            return list(x)

        return double_nested

    a = nested()
    return a(("a", "b"))


print(test())

```
outputs
```
['a', 'b']
```

ruff complains:
```
test.py:1:29: TCH003 Move standard library import `collections.abc.Callable` into a type-checking block  
test.py:1:39: TCH003 Move standard library import `collections.abc.Collection` into a type-checking block
```

appeasing ruff
```
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Callable, Collection


def test():
    def nested() -> Callable[[Collection[str]], list[str]]:
        def double_nested(x: Collection[str]) -> list[str]:
            return list(x)

        return double_nested

    a = nested()
    return a(("a", "b"))


print(test())

```
breaks the code:
```
Traceback (most recent call last):
  File "c:\Programs\PCGUserdir\Repos\SmartSensorBus_configurator\tempCodeRunnerFile.py", line 18, in <module>
    print(test())
          ^^^^^^
  File "c:\Programs\PCGUserdir\Repos\SmartSensorBus_configurator\tempCodeRunnerFile.py", line 8, in test
    def nested() -> Callable[[Collection[str]], list[str]]:
                    ^^^^^^^^
NameError: name 'Callable' is not defined. Did you mean: 'callable'?
```

the command i used to invoke ruff: `python -m ruff .`
my pyproject.toml ruff settings:
```
[tool.ruff]
line-length = 100
ignore-init-module-imports = true
extend-select = [
	"W",      # pydocstyle warnings
	"C90",    # mccabe complexity
	"I",      # import sorting
	"N",      # pep8 naming
	"UP",     # old syntax/constructs
	"YTT",    # old syntax/constructs
	"B",      # common sources of bugs
	"A",      # shadowing builtins
	"COM",    # trailing commas
	"C4",     # comprehensions
	"EXE",    # shebangs / executable .py files
	"ISC",    # implicit string concatenation
	"PT",     # pytest
	"Q",      # quotes
	"RET502", # missing return
	"RET503", # missing return
	"SIM",    # simplify code
	"TCH",    # type checking imports
	"ARG",    # unused arguments
	"PTH",    # use pathlib
	"PLE",    # pylint errors
]
ignore = [
	"E501",   # let black handle line length
	"COM812", # let black handle missing trailing commas
]
unfixable = [
	"F841", # unused variable
	"F401", # unused import
]
```

ruff version: `ruff 0.0.261`
python version: `Python 3.11.2`

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

It turns out that if `from __future__ import annotations` isn't enabled, then annotations on function arguments or return values _are_ required at runtime, as in this example:

```py
from collections.abc import Callable, Collection

def test():
    def nested(x: Callable) -> Callable[[Collection[str]], list[str]]:
        def double_nested(x: Collection[str]) -> list[str]:
            return list(x)

        return double_nested

    a = nested(None)
    return a(("a", "b"))

print(test())
```

To be consistent with our logic for this rule, we thus need to avoid raising `TCH` errors here.

We might want to change the semantics of the rule such that it tells you to move the types into a `TYPE_CHECKING` block _and_ quote them, but as of now, users that follow these suggestions will break their code. (As a corollary, these rules effectively require that you're using `from __future__ import annotations` to be useful.)

Closes #4020.

### CODE REVIEW

File: crates/ruff/src/checkers/ast/mod.rs [hunk 1]
```diff
@@ -598,14 +598,9 @@ where
                     self.visit_expr(expr);
                 }
 
-                // If we're in a class or module scope, then the annotation needs to be
-                // available at runtime.
```
Comment (charliermarsh) [inline crates/ruff/src/checkers/ast/mod.rs:602]: (This applies to `AnnAssign` statements, not function definitions.)
