### PR TITLE
Include list of fixed files in `stderr` output

### LINKED ISSUE #1667: Error fixes are logged without indicating file names
Example output from running `ruff` via a git pre-commit hook:

```
ruff.....................................................................Failed
- hook id: ruff
- files were modified by this hook

Found 1 error(s) (1 fixed, 0 remaining).
```

Locally, it's possible to do something like `git status` to see which files were changed as a result of the hook. But when these hooks are run in a CI run for example, seeing the file names in ruff's output would be useful

### PR DESCRIPTION
**Pull request by charliermarsh**
This PR adds the list of fixed files to Ruff's output (send to `stderr`, and omitted for `--silent` and `--quiet` settings):

Screen Shot 2023-01-06 at 7 07 57 PM

Closes #1667.

### CODE REVIEW

File: src/linter.rs [hunk 1]
```diff
@@ -212,6 +214,9 @@ pub fn lint_path(
         let (transformed, fixed, messages) = lint_fix(&contents, path, package, settings)?;
         if fixed > 0 {
             if matches!(autofix, fixer::Mode::Apply) {
+                if level >= LogLevel::Default {
+                    eprintln!("Fixing {} error(s) in {}", fixed, fs::relativize_path(path));
```
Comment (andersk) [inline src/linter.rs:218]: Are we going with “violation(s)” here too?

Comment (charliermarsh) [reply src/linter.rs:218]: Eventually, but for now I wanted it to be consistent with the rest of the output (which says "error(s)" at the bottom).

Also: we may continue to say "error" in both places, because an error will be a severity level for a violation (so, in theory, we could say "X errors and Y warnings").

**Comment by charliermarsh** [comment]
@smackesey - Not urgent but just looking for some user feedback -- does this seem useful, or too noisy? (I reverted this change for now so it won't go out yet.)
