### PR TITLE
Fix add-required-import with multi-line offsets

### LINKED ISSUE #2944: [Infinite loop] with missing required import rule
- target file contents before ruff: https://gist.github.com/underyx/ad1478d388cd61bfcb89e25a5ea3ddde
  - after ruff: https://gist.github.com/underyx/5741723fd6ffd373ec96f7967552c123 
  - re-running ruff keeps reporting `100 fixed` even on the 'after ruff' file
- ruff.toml contents: https://gist.github.com/underyx/c0b8d0b6d9c4dd6d1be9447185eaebab
- ruff 0.0.247

```terminal
$ ruff --version
ruff 0.0.247
$ ruff src/semgrep/app/version.py --select I002 --fix --no-cache

error: Failed to converge after 100 iterations.

This indicates a bug in `ruff`. If you could open an issue at:

    https://github.com/charliermarsh/ruff/issues/new?title=%5BInfinite%20loop%5D

...quoting the contents of `src/semgrep/app/version.py`, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

src/semgrep/app/version.py:1:1: I002 Missing required import: `from __future__ import annotations`
Found 101 errors (100 fixed, 1 remaining).
```

### PR DESCRIPTION
**Pull request by charliermarsh**
Closes #2944.

### CODE REVIEW

File: crates/ruff/src/rules/isort/helpers.rs [hunk 1]
```diff
@@ -110,7 +110,7 @@ pub fn find_splice_location(body: &[Stmt], locator: &Locator) -> Location {
 
     // Find the first token that isn't a comment or whitespace.
     let contents = locator.skip(splice);
-    for (.., tok, end) in lexer::make_tokenizer(contents).flatten() {
+    for (.., tok, end) in lexer::make_tokenizer_located(contents, splice).flatten() {
```
Comment (charliermarsh) [inline crates/ruff/src/rules/isort/helpers.rs:113]: We're generating an offset here, so it needs to be relative to the current `splice`!
