### PR TITLE
[`pylint`] Fix `PLW3301` auto-fix with generators

### LINKED ISSUE #4410: PLW3301: incorrect autofix when using generator expression
The autofix for `PLW3301` generates incorrect code if the nested call is using a generator expression.

## Example

PLW3301.py:
```python
x = max(1, max(i for i in range(10)))
```

## Observed 
```
ruff --isolated --diff --select PLW3301  PLW3301.py
--- PLW3301.py
+++ PLW3301.py
@@ -1 +1 @@
-x = max(1, max(i for i in range(10)))
+x = max(1, (i for i in range(10)))

Would fix 1 error.
```

## Issue

This is incorrect. `max` [takes either an iterable, or a variable number of arguments, but not both](https://docs.python.org/3/library/functions.html#max):
```
python -c "max(1, (i for i in range(10)))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: '>' not supported between instances of 'generator' and 'int'
```                                        

## Expected

The correct fix would be:
```
max(1, *(i for i in range(10)))
```

## Ruff Version

```
ruff --version
ruff 0.0.267
```

### PR DESCRIPTION
**Pull request by JonathanPlasse**
- Close #4410

### CODE REVIEW

File: crates/ruff/src/rules/pylint/rules/nested_min_max.rs [hunk 1]
```diff
@@ -77,7 +77,18 @@ fn collect_nested_args(context: &Context, min_max: MinMax, args: &[Expr]) -> Vec
                     continue;
                 }
             }
-            new_args.push(arg.clone());
+            let new_arg = if arg.is_generator_exp_expr() {
```
Comment (charliermarsh) [inline crates/ruff/src/rules/pylint/rules/nested_min_max.rs:80]: I don't think this is quite sufficient, since `max(1, max(a))` will still be flagged, where `a` could be a generator. In fact, I think `a` _has_ to be an iterable, so `max(1, a)` will fail regardless?

File: crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLW3301_nested_min_max.py.snap [hunk 2]
```diff
@@ -191,7 +191,42 @@ nested_min_max.py:18:1: PLW3301 Nested `min` calls can be flattened
...
+   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ PLW3301
+   |
+   = help: Flatten nested `max` calls
+
+ℹ Suggested fix
+22 22 | 
+23 23 | # Handle generator expressions.
+24 24 | min(1, min(i for i in range(10)))
+25    |-max(1, max(i for i in range(10)))
+   25 |+max(1, *(i for i in range(10)))
```
Comment (charliermarsh) [inline crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLW3301_nested_min_max.py.snap:230]: Does this eagerly evaluate the generator?

Comment (JonathanPlasse) [reply crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__PLW3301_nested_min_max.py.snap:230]: This code
```python
def fn1():
    for i in range(10):
        print(i)
        yield i

def fn2():
    print('fn2')
    return 1

max(1, *fn1(), fn2())
```
prints this
```console
0
1
2
3
4
5
6
7
8
9
fn2
```
It is eager otherwise, `fn2` would be printed first.

File: crates/ruff/src/rules/pylint/rules/nested_min_max.rs (hunk 1 above)
Comment (JonathanPlasse) [reply crates/ruff/src/rules/pylint/rules/nested_min_max.rs]: Indeed, a single `min`/`max` argument has to be iterable according to typeshed.
