### PR TITLE
Invert quote-style when generating code within f-strings

### LINKED ISSUE #4321: [Autofix error] FLY002 fails with `f"{' '}"`
In ruff 99a755f936ebd73cdd1bfccbc121c31d4b27751e, the following snippet causes the autofix FLY002 from the flynt rules to introduce a syntax error:

```python
f"{' '}"
```

```
$ ruff --no-cache --select FLY002 --fix code.py
error: Autofix introduced a syntax error. Reverting all changes.

This indicates a bug in `ruff`. If you could open an issue at:

    https://github.com/charliermarsh/ruff/issues/new?title=%5BAutofix%20error%5D

...quoting the contents of `a.py`, the rule codes FLY002, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

a.py:161:80: FLY002 Consider `f"{ZIP}, {IMAGE}"` instead of string join
Found 1 error.
```

This was originally discovered in https://github.com/aws/aws-sam-cli/blob/abb6fd069ce79668c7a811758a732970c5be1a66/samcli/commands/init/command.py#L161

### LINKED ISSUE #4322: [Autofix error] UP018 autofix fails when str() call is inside f-string: `f"{str()}"`
In ruff https://github.com/charliermarsh/ruff/commit/99a755f936ebd73cdd1bfccbc121c31d4b27751e, the following snippet causes the autofix UP018 from the pyupgrade rules to introduce a syntax error:

```python
f"{str()}"
```

```
$ ./ruff --no-cache --select UP018 --fix code.py

error: Autofix introduced a syntax error. Reverting all changes.

This indicates a bug in `ruff`. If you could open an issue at:

    https://github.com/charliermarsh/ruff/issues/new?title=%5BAutofix%20error%5D

...quoting the contents of `code.py`, the rule codes UP018, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

code.py:1:4: UP018 Unnecessary call to `str`
Found 1 error.
```

This was originally discovered in https://github.com/Scille/parsec-cloud/blob/114c80f2349e555ebac1aef132ac9289de7c8dff/misc/releaser.py#L120

### LINKED ISSUE #4323: [Autofix error] PIE810 autofix fails when inside f-string: `f"{key.startswith('a') or key.startswith('b')}"`
In ruff https://github.com/charliermarsh/ruff/commit/99a755f936ebd73cdd1bfccbc121c31d4b27751e, the following snippet causes the autofix PIE810 from the flake8-pie rules to introduce a syntax error:

```python
f"{key.startswith('a') or key.startswith('b')}"
```

```
$ ./ruff --no-cache --select PIE810 --fix code.py 

error: Autofix introduced a syntax error. Reverting all changes.

This indicates a bug in `ruff`. If you could open an issue at:

    https://github.com/charliermarsh/ruff/issues/new?title=%5BAutofix%20error%5D

...quoting the contents of `code.py`, the rule codes PIE810, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

code.py:1:4: PIE810 Call `startswith` once with a `tuple`
Found 1 error.
```

This was originally discovered in https://github.com/Mojino01/hugging_face/blob/3dae0d7b4fb8d7e9383b893e4e1799191bb2ab7b/src/transformers/models/luke/convert_luke_original_pytorch_checkpoint_to_pytorch.py#L81

### LINKED ISSUE #4324: [Autofix error] RUF005 autofix fails inside f-string: `f"{a() + ['b']}"`
In ruff https://github.com/charliermarsh/ruff/commit/99a755f936ebd73cdd1bfccbc121c31d4b27751e, the following snippet causes the autofix RUF005 to introduce a syntax error:

```python
f"{a() + ['b']}"
```

```
$ ./ruff --no-cache --select RUF005 --fix code.py

error: Autofix introduced a syntax error. Reverting all changes.

This indicates a bug in `ruff`. If you could open an issue at:

    https://github.com/charliermarsh/ruff/issues/new?title=%5BAutofix%20error%5D

...quoting the contents of `code.py`, the rule codes RUF005, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

code.py:1:4: RUF005 Consider `[*a(), "b"]` instead of concatenation
Found 1 error.
```

This was originally discovered in https://github.com/Mojino01/hugging_face/blob/3dae0d7b4fb8d7e9383b893e4e1799191bb2ab7b/src/transformers/pipelines/base.py#L1181

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

When we generate source code from an AST (via `Generator`), we have a preferred quote style, based on the inferred quote style in the file. Unfortunately, when we try to generate autofixes within f-strings, the `Generator` is unaware of the fact that we're "inside" an f-string, and so continues to use that preferred quote style, which often leads to syntax errors.

This PR modifies our logic to detect when we're inside a single-quoted f-string, and then pass in the "inverted" quote style based on whatever was used to quote that f-string. This in turn requires that we track all f-strings, and are able to map from the current expression to the surrounding f-strings.

Two considerations here:

1. The quote style that we provide to `Generator` is really a "preferred" quote style. The `Generator` will "ignore" that preference if, e.g., it lets us avoid escaping a quote within a string, similar to Black's preferences. This would be problematic within f-strings. However, f-strings can't contain backslashes (it's a syntax error?), so... it might be fine?
2. This doesn't really deal with _nested_ f-strings. I'm not sure what we want to do in those cases. The grammar is so limiting and complicated. We may want to avoid fixing issues within nested f-strings altogether?

Closes #4322.

Closes #4324.

Closes #4323.

Closes #4321.

### CODE REVIEW

File: crates/ruff/src/checkers/ast/mod.rs [hunk 1]
```diff
@@ -134,6 +135,53 @@ impl<'a> Checker<'a> {
         }
         noqa::rule_is_ignored(code, offset, self.noqa_line_for, self.locator)
     }
+
+    /// Create a [`Generator`] to generate source code based on the current AST state.
+    pub fn generator(&self) -> Generator {
```
Comment (charliermarsh) [inline crates/ruff/src/checkers/ast/mod.rs:140]: I don't know where this belongs -- it requires the `Context`, `Indexer`, `Locator`, and `Stylist`, so right now it lives on `Checker`...

File: crates/ruff/src/rules/flake8_bandit/rules/hardcoded_sql_expression.rs [hunk 2]
```diff
@@ -62,14 +62,14 @@ fn unparse_string_format_expression(checker: &mut Checker, expr: &Expr) -> Optio
         }) => {
             let Some(parent) = checker.ctx.expr_parent() else {
                 if any_over_expr(expr, &has_string_literal) {
-                    return Some(unparse_expr(expr, checker.stylist));
+                    return Some(unparse_expr(expr, checker.generator()));
```
Comment (charliermarsh) [inline crates/ruff/src/rules/flake8_bandit/rules/hardcoded_sql_expression.rs:65]: These are all mechanical.

File: crates/ruff_python_ast/src/source_code/indexer.rs [hunk 3]
```diff
@@ -59,25 +64,34 @@ impl Indexer {
...
+                    triple_quoted,
+                    kind,
                     ..
-                } => string_ranges.push(*range),
+                } => {
+                    if *triple_quoted {
+                        triple_quoted_string_ranges.push(*range);
+                    }
+                    if matches!(kind, StringKind::FString | StringKind::RawFString) {
+                        f_string_ranges.push(*range);
```
Comment (charliermarsh) [inline crates/ruff_python_ast/src/source_code/indexer.rs:81]: We now track f-string ranges, which lets us do a binary search to find the containing f-string whenever we need to fix within an f-string.

**Comment by charliermarsh** [comment]
As part of this effort... we may want to consider `Generator` to be deprecated, or an anti-pattern. In addition to this problem (it's context-independent), it also removes trivia, like comments. It is very useful, and we don't have a great replacement for it, but...

**Review by MichaReiser — COMMENTED** [review]
> This PR modifies our logic by "inverting" the preferred quote style whenever we're inside a single-quoted f-string. This in turn requires that we track all f-strings, and are able to map from the current expression to the surrounding f-strings.

My understanding is that the preferred quote style only reflects the most used quote sign. This does not guarantee that the source code contains no fstrings with the *not preferred* fstring. 

> This doesn't really deal with nested f-strings. I'm not sure what we want to do in those cases. The grammar is so limiting and complicated. We may want to avoid fixing issues within nested f-strings altogether?

An alternative would be to make this a `manual` fix. This won't be very helpful now because our default text renderer doesn't show fixes (we should improve our diagnostics). 

How difficult do you think would it be to add source map support to the `Generator`? We could then generate the code for the enclosing expression or statement and then extract the fstring range. They way this could work is that the generator writes a source map entry at the start and end of every node, mapping the node's start/end offset to the offset in the generated source (similar to the Printer in the formatter)

File: crates/ruff/src/checkers/ast/mod.rs [hunk 4]
```diff
@@ -134,6 +135,53 @@ impl<'a> Checker<'a> {
...
+                if start < range.start() {
+                    std::cmp::Ordering::Greater
+                } else if range.contains(start) {
+                    std::cmp::Ordering::Equal
+                } else {
+                    std::cmp::Ordering::Less
+                }
+            }) else {
+                return None;
+            };
```
Comment (MichaReiser) [inline crates/ruff/src/checkers/ast/mod.rs:163]: Nit: I think it would be good to move this logic to the `Indexer`. It makes very explicit assumption about `string_ranges` and it may not be obvious to someone working on `Indexer` that some code is making these assumptions

File: crates/ruff_python_ast/src/source_code/indexer.rs [hunk 5]
```diff
@@ -97,6 +111,12 @@ impl Indexer {
         &self.triple_quoted_string_ranges
     }
 
+    /// Return a slice of all ranges that include an f- string. The ranges are sorted by
+    /// [`TextRange::start`] in increasing order. No two ranges are overlapping.
+    pub fn f_string_ranges(&self) -> &[TextRange] {
+        &self.f_string_ranges
+    }
```
Comment (MichaReiser) [inline crates/ruff_python_ast/src/source_code/indexer.rs:118]: I would prefer to avoid exposing too much of the assumption on how the ranges is stored and instead provide semantic methods to find an fstring, given a range.

File: crates/ruff_python_ast/src/source_code/indexer.rs [hunk 6]
```diff
@@ -59,25 +64,34 @@ impl Indexer {
...
-                    triple_quoted: true,
+                    triple_quoted,
+                    kind,
                     ..
-                } => string_ranges.push(*range),
+                } => {
+                    if *triple_quoted {
+                        triple_quoted_string_ranges.push(*range);
+                    }
+                    if matches!(kind, StringKind::FString | StringKind::RawFString) {
```
Comment (MichaReiser) [inline crates/ruff_python_ast/src/source_code/indexer.rs:80]: Can an fstring be triple quoted? If not, use an `else if` or use two separate `match` arms, one for triple-quoted strings and another for fstrings.

File: crates/ruff_python_ast/src/helpers.rs [hunk 7]
```diff
@@ -17,26 +17,23 @@ use smallvec::SmallVec;
...
 use crate::call_path::CallPath;
 use crate::newlines::UniversalNewlineIterator;
-use crate::source_code::{Generator, Indexer, Locator, Stylist};
+use crate::source_code::{Generator, Indexer, Locator};
 use crate::statement_visitor::{walk_body, walk_stmt, StatementVisitor};
 
 /// Generate source code from an [`Expr`].
-pub fn unparse_expr(expr: &Expr, stylist: &Stylist) -> String {
-    let mut generator: Generator = stylist.into();
+pub fn unparse_expr(expr: &Expr, mut generator: Generator) -> String {
```
Comment (MichaReiser) [inline crates/ruff_python_ast/src/helpers.rs:24]: For another PR: Should we move these methods to `Generator` instead, now that they always require a generator.

```
generator.unparse_expr(expr) 
// or

generator.generate_expr(expr)
```

**Review by MichaReiser — APPROVED** [review]

**Comment by charliermarsh** [comment]
> Edit: Your implementation handles this correctly, I think.

👍 Yeah, sorry, the implementation does do this correctly, but I'll improve the summary.

File: crates/ruff_python_ast/src/source_code/indexer.rs (hunk 6 above)
Comment (charliermarsh) [reply crates/ruff_python_ast/src/source_code/indexer.rs:80]: It can! We actually don't need to use those anywhere since we only care about single-quoted f-strings... But it seems strange to omit them.

File: crates/ruff/src/checkers/ast/mod.rs (hunk 4 above)
Comment (charliermarsh) [reply crates/ruff/src/checkers/ast/mod.rs:163]: Good idea.

**Comment by charliermarsh** [comment]
> How difficult do you think would it be to add source map support to the Generator? We could then generate the code for the enclosing expression or statement and then extract the fstring range. They way this could work is that the generator writes a source map entry at the start and end of every node, mapping the node's start/end offset to the offset in the generated source (similar to the Printer in the formatter)

Can you elaborate on this a bit more? What does this buy us? (Genuinely asking, not objecting.)

File: crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP018.py.snap [hunk 8]
```diff
@@ -125,5 +127,22 @@ UP018.py:26:1: UP018 [*] Unnecessary call to `bytes`
...
+28 28 | f"{str()}"
+
+UP018.py:28:4: UP018 [*] Unnecessary call to `str`
+   |
+28 | bytes(b"""
+29 | foo""")
+30 | f"{str()}"
+   |    ^^^^^ UP018
+   |
+   = help: Replace with `str`
```
Comment (konstin) [inline crates/ruff/src/rules/pyupgrade/snapshots/ruff__rules__pyupgrade__tests__UP018.py.snap:139]: that suggestion looks wrong

**Comment by MichaReiser** [comment]
> Can you elaborate on this a bit more? What does this buy us? (Genuinely asking, not objecting.)

I wrote this before I understood that your fix solves the problem. The main benefit would be that it would make the Generator context aware. You won't need any special handling because you generate on a statement level.
