### PR TITLE
Avoid panics for implicitly-concatenated docstrings

### LINKED ISSUE #3543: [Panic] thread 'main' panicked at 'byte index 143 is not a char boundary; when scanning file
Ruff 0.0.255

command
```
ruff .
```

crash
```
error: `ruff` crashed. This indicates a bug in `ruff`. If you could open an issue at:

https://github.com/charliermarsh/ruff/issues/new?title=%5BPanic%5D

quoting the executed command, along with the relevant file contents and `pyproject.toml` settings, we'd be very appreciative!

thread 'main' panicked at 'byte index 143 is not a char boundary; it is inside '\u{2ecdf}' (bytes 140..144) of `"""SCons.Tool.python

Regi""assert""con"]" tinue";"sters"except"  the Python scanner for the suppor󂩢ed Python source file suffixes.

""""𮳟s"`', crates/ruff_python_ast/src/str.rs:27:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```
[4621382747python30.py.zip](https://github.com/charliermarsh/ruff/files/10982790/4621382747python30.py.zip)

### LINKED ISSUE #3585: [Autofix] Failed to autofix oneline python file
Ruff 1dd3cbd047beda01a7833e1b20e10e745757fe3e
No config
```
ruff . --fix
```
on
```
"()"""" Wrapper namespace for re type aliases. """
```
cause error
```
error: Autofix introduced a syntax error. Reverting all changes.

This indicates a bug in `ruff`. If you could open an issue at:

    https://github.com/charliermarsh/ruff/issues/new?title=%5BAutofix%20error%5D

...quoting the contents of `/home/rafal/Desktop/RunEveryCommand/Ruff/Broken/42002re (147th copy)0.py`, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

```

[42002re (147th copy)0.py.zip](https://github.com/charliermarsh/ruff/files/11006158/42002re.147th.copy.0.py.zip)

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

In the rare event that a docstring contains an implicit string concatenation, we currently have the potential to panic, because we assume that if a string starts with triple quotes, it _ends_ with triple quotes. But with implicit concatenation, that's not the case: a single `Expr` could start and end with different quote styles, because it can contain multiple string tokens.

Supporting these "properly" is pretty hard. In some cases it's hard to even know what the "right" behavior is. So for now, I'm just detecting and warning, which is better than a panic.

Closes #3543.

Closes #3585.

### CODE REVIEW

File: crates/ruff/src/checkers/ast/mod.rs [hunk 1]
```diff
@@ -5162,6 +5164,16 @@ impl<'a> Checker<'a> {
...
                 ));
 
+                if pydocstyle::helpers::should_ignore_docstring(contents) {
+                    warn_user!(
+                        "Docstring at {}:{}:{} contains implicit string concatenation; ignoring...",
+                        relativize_path(self.path),
+                        expr.location.row(),
+                        expr.location.column() + 1
+                    );
+                    continue;
```
Comment (charliermarsh) [inline crates/ruff/src/checkers/ast/mod.rs:5174]: Ideally this would be a diagnostic but I'm not sure that it fits any of our existing diagnostics under the `pydocstyle` category.

File: crates/ruff_python_ast/src/str.rs [hunk 2]
```diff
@@ -67,6 +69,15 @@ pub fn is_triple_quote(content: &str) -> bool {
     TRIPLE_QUOTE_STR_PREFIXES.contains(&content) || TRIPLE_QUOTE_BYTE_PREFIXES.contains(&content)
 }
 
+/// Return `true` if the string expression is an implicit concatenation.
+pub fn is_implicit_concatenation(content: &str) -> bool {
+    lexer::lex(content, Mode::Module)
+        .flatten()
+        .filter(|(_, tok, _)| matches!(tok, Tok::String { .. }))
+        .nth(1)
+        .is_some()
```
Comment (MichaReiser) [inline crates/ruff_python_ast/src/str.rs:78]: This change regresses all our benchmarks by 3-5%. I assume that calling the lexer is the expensive operation. 

```
❯ cargo benchmark --baseline=main
    Finished bench [optimized] target(s) in 0.10s
     Running benches/linter.rs (target/release/deps/linter-b1b4f7dad7c3da18)
linter/default-rules/numpy/globals.py
                        time:   [114.58 µs 114.69 µs 114.81 µs]
                        thrpt:  [25.700 MiB/s 25.727 MiB/s 25.753 MiB/s]
                 change:
                        time:   [+3.4859% +3.6247% +3.7608%] (p = 0.00 < 0.05)
                        thrpt:  [-3.6245% -3.4979% -3.3685%]
                        Performance has regressed.
Found 4 outliers among 100 measurements (4.00%)
  4 (4.00%) high mild
linter/default-rules/pydantic/types.py
                        time:   [2.2319 ms 2.2410 ms 2.2508 ms]
                        thrpt:  [11.331 MiB/s 11.380 MiB/s 11.427 MiB/s]
                 change:
                        time:   [+2.6956% +2.9809% +3.2544%] (p = 0.00 < 0.05)
                        thrpt:  [-3.1519% -2.8946% -2.6248%]
                        Performance has regressed.
Found 20 outliers among 100 measurements (20.00%)
  15 (15.00%) low severe
  3 (3.00%) high mild
  2 (2.00%) high severe
linter/default-rules/numpy/ctypeslib.py
                        time:   [1.0648 ms 1.0652 ms 1.0658 ms]
                        thrpt:  [15.623 MiB/s 15.632 MiB/s 15.638 MiB/s]
                 change:
                        time:   [+3.7858% +3.8922% +4.0261%] (p = 0.00 < 0.05)
                        thrpt:  [-3.8703% -3.7464% -3.6477%]
                        Performance has regressed.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high severe
linter/default-rules/large/dataset.py
                        time:   [5.0569 ms 5.0704 ms 5.0813 ms]
                        thrpt:  [8.0064 MiB/s 8.0236 MiB/s 8.0450 MiB/s]
                 change:
                        time:   [+4.4705% +4.9010% +5.3636%] (p = 0.00 < 0.05)
                        thrpt:  [-5.0906% -4.6720% -4.2792%]
                        Performance has regressed.

linter/all-rules/numpy/globals.py
                        time:   [266.26 µs 266.46 µs 266.64 µs]
                        thrpt:  [11.066 MiB/s 11.074 MiB/s 11.082 MiB/s]
                 change:
                        time:   [+5.0624% +5.4244% +5.7740%] (p = 0.00 < 0.05)
                        thrpt:  [-5.4588% -5.1453% -4.8185%]
                        Performance has regressed.
Found 7 outliers among 100 measurements (7.00%)
  3 (3.00%) high mild
  4 (4.00%) high severe
linter/all-rules/pydantic/types.py
                        time:   [3.6534 ms 3.6759 ms 3.6976 ms]
                        thrpt:  [6.8973 MiB/s 6.9380 MiB/s 6.9807 MiB/s]
                 change:
                        time:   [+0.0982% +0.5182% +0.9516%] (p = 0.02 < 0.05)
                        thrpt:  [-0.9427% -0.5156% -0.0981%]
                        Change within noise threshold.
Found 2 outliers among 100 measurements (2.00%)
  2 (2.00%) high mild
linter/all-rules/numpy/ctypeslib.py
                        time:   [2.2603 ms 2.2640 ms 2.2688 ms]
                        thrpt:  [7.3392 MiB/s 7.3548 MiB/s 7.3667 MiB/s]
                 change:
                        time:   [+4.0998% +4.3497% +4.6664%] (p = 0.00 < 0.05)
                        thrpt:  [-4.4583% -4.1684% -3.9383%]
                        Performance has regressed.
Found 13 outliers among 100 measurements (13.00%)
  4 (4.00%) high mild
  9 (9.00%) high severe
linter/all-rules/large/dataset.py
                        time:   [8.6941 ms 8.6980 ms 8.7021 ms]
                        thrpt:  [4.6751 MiB/s 4.6773 MiB/s 4.6793 MiB/s]
                 change:
                        time:   [+1.8525% +2.0888% +2.3387%] (p = 0.00 < 0.05)
                        thrpt:  [-2.2853% -2.0461% -1.8188%]
                        Performance has regressed.
Found 25 outliers among 100 measurements (25.00%)
  13 (13.00%) low severe
  5 (5.00%) low mild
  3 (3.00%) high mild
  4 (4.00%) high severe
```

Can we apply a heuristic to short-circuit the call into the lexer? Or implement the test explicitly by:

* Testing if the start and end quotes are identical: if not -> implicit concatenation 
* find the closing quote character (ignoring escaped quotes): If it is at the end of contents -> all good, if not -> concatenation. We should be able to use `find` only for docstrings, if my assumption that triple quotes can't be escaped is correct

**Review by MichaReiser — COMMENTED** [review]
The code looks good, but we should investigate the performance regression.

File: crates/ruff_python_ast/src/str.rs (hunk 2 above)
Comment (charliermarsh) [reply crates/ruff_python_ast/src/str.rs:78]: Great call, horray for continuous benchmarking! Let me play around with this. I'm sure we can do better.

Comment (charliermarsh) [reply crates/ruff_python_ast/src/str.rs]: Alright, let's see if this new version does any better...

File: crates/ruff_python_ast/src/str.rs [hunk 3]
```diff
@@ -67,6 +69,15 @@ pub fn is_triple_quote(content: &str) -> bool {
     TRIPLE_QUOTE_STR_PREFIXES.contains(&content) || TRIPLE_QUOTE_BYTE_PREFIXES.contains(&content)
 }
 
+/// Return `true` if the string expression is an implicit concatenation.
+pub fn is_implicit_concatenation(content: &str) -> bool {
```
[the remark this answers is not in the document]
Comment (charliermarsh) [reply crates/ruff_python_ast/src/str.rs:71]: I think I prefer this interface at-present since it's consistent with the rest of this module, which operates directly on strings (and thus has no dependencies, isn't coupled to the AST, etc.).

File: crates/ruff_python_ast/src/str.rs (hunk 2 above)
Comment (charliermarsh) [reply crates/ruff_python_ast/src/str.rs]: This looks much _better_ but there's still a noticeable difference in the NumPy case.

Comment (charliermarsh) [reply crates/ruff_python_ast/src/str.rs]: Actually... is this just noise? The default-rules benchmark shouldn't be affected by this change.

Comment (MichaReiser) [reply crates/ruff_python_ast/src/str.rs]: 1-2% changes are most often just noise. Especially if they are specific to a single test.

File: crates/ruff_python_ast/src/str.rs [hunk 4]
```diff
@@ -67,15 +67,55 @@ pub fn is_triple_quote(content: &str) -> bool {
...
```
Comment (MichaReiser) [inline crates/ruff_python_ast/src/str.rs:71]: Could you add a few examples (ideally, by using doctetsts)?

File: crates/ruff_python_ast/src/str.rs [hunk 5]
```diff
@@ -67,15 +67,55 @@ pub fn is_triple_quote(content: &str) -> bool {
...
+    let leading_quote_str = leading_quote(content).unwrap();
+    let trailing_quote_str = trailing_quote(content).unwrap();
```
Comment (MichaReiser) [inline crates/ruff_python_ast/src/str.rs:73]: Can we return `false` if the string does not have any quotes (avoids the potential panic)
```suggestion
    let Some(leading_quote_str) = leading_quote(content) else { return false; }
    let Some(trailing_quote_str) = trailing_quote(content) else { return false; }
```

**Review by MichaReiser — APPROVED** [review]
Neat! Thanks for taking the time to improve the performance.

File: crates/ruff_python_ast/src/str.rs [hunk 6]
```diff
@@ -67,15 +67,55 @@ pub fn is_triple_quote(content: &str) -> bool {
...
+
+    // Short-circuit: if the trailing quote doesn't match the _expected_ trailing quote, then
+    // the string is implicitly concatenated.
+    if trailing_quote_str != trailing_quote(trailing_quote_str).unwrap() {
+        return true;
+    }
```
[the remark this answers is not in the document]
Comment (charliermarsh) [reply crates/ruff_python_ast/src/str.rs:79]: D'oh, this is supposed to be `trailing_quote(leading_quote_str)` on the right-hand side. Wasn't caught by tests since it's just a short-circuit...

To be clear, the trick is that the leading quote includes the string "kind" prefix.

So given a string like:

```py
u"""abc def"""
```

The leading quote would be `u"""`, and the trailing quote would be `"""`.

File: crates/ruff_python_ast/src/str.rs [hunk 7]
```diff
@@ -67,15 +67,55 @@ pub fn is_triple_quote(content: &str) -> bool {
...
+
+    let mut offset = leading_quote_str.len();
```
[the remark this answers is not in the document]
Comment (charliermarsh) [reply crates/ruff_python_ast/src/str.rs:81]: Make :clap: impossible :clap: states :clap: unrepresentable

File: crates/ruff_python_ast/src/str.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (MichaReiser) [reply crates/ruff_python_ast/src/str.rs]: I'm still somewhat confused. Shouldn't it be `leading_quote_str != trailing_quote_str`?

File: crates/ruff_python_ast/src/str.rs (hunk 7 above)
[the remark this answers is not in the document]
Comment (charliermarsh) [reply crates/ruff_python_ast/src/str.rs]: Fixed, I had to use `let mut rest` and reassign as I went -- hopefully that matches your intention here.

File: crates/ruff_python_ast/src/str.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (charliermarsh) [reply crates/ruff_python_ast/src/str.rs]: No, because `u"""` and `"""` is a valid leading-trailing quote pair.

What we want to know is that if the string has a leading quote of `u"""`, then its expected trailing quote is `"""`. Here, we're checking if that expected trailing quote matches the _actual_ trailing quote.

For example, given:

```
u"""abc""" 'def'
```

The leading quote would be `u"""`. The trailing quote would be `'`. The _expected_ trailing quote would be `"""`. Since `'` does not equal `"""`, we'd return `false`.

[the remark this answers is not in the document]
Comment (charliermarsh) [reply crates/ruff_python_ast/src/str.rs]: I'd like to make this clearer since it's evidently too confusing :joy: Any suggestions?

[the remark this answers is not in the document]
Comment (MichaReiser) [reply crates/ruff_python_ast/src/str.rs]: Uhh, python quotes are confusing. Why so many :confused: 

Paste your reply as a comment :)
