### PR TITLE
Fix expected-indentation errors with end-of-line comments

### LINKED ISSUE #4417: Indented-block checks fail to respect inline comment
Given:

```py
def main() -> None:  # Comment
    print("Retrieving data...")


def main() -> None: 
# Comment
    print("Retrieving data...")


def main() -> None: 
    # Comment
    print("Retrieving data...")


def main() -> None: 
    print("Retrieving data...")
```

We report:

```
foo.py:1:1: E112 Expected an indented block
foo.py:2:1: E113 Unexpected indentation
foo.py:6:1: E115 Expected an indented block (comment)
```

Meanwhile, pycodestyle reports:

```
foo.py:6:1: E115 expected an indented block (comment)
```

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Given code like:

```py
if False:  #
    print()
```

The token stream will contain a comment, followed by a newline. At present, we end up creating a separate logical line for _just_ the newline, which throws off our logic around expected-indentation rules, which needs to look back at the previous newline to determine the appropriate indentation.

I've looked at the lexer to better understand the logic around when to expect a newline token (following a comment). My understanding is that there should _always_ be a newline unless the comment appears at the start of a (logical?) line, since the only codepath that consumes but doesn't generate a newline is via `eat_indentation`.

Closes #4417.

### CODE REVIEW

File: crates/ruff/src/rules/pycodestyle/rules/logical_lines/mod.rs [hunk 1]
```diff
@@ -100,9 +101,25 @@ impl<'a> LogicalLines<'a> {
...
+                    // appears at the start of a logical line.
+                    if let Some((token, ..)) = iter.peek() {
+                        let token_kind = TokenKind::from_token(token);
+                        if matches!(
+                            token_kind,
+                            TokenKind::Newline | TokenKind::NonLogicalNewline
+                        ) {
+                            continue;
+                        }
+                    }
```
Comment (charliermarsh) [inline crates/ruff/src/rules/pycodestyle/rules/logical_lines/mod.rs:119]: Alternatively, we may be able to get away with checking if this is the first token in the line? In theory that should also work. It's arguably more reliant on details of the lexer, but it's also making the expectation more explicit.

**Comment by charliermarsh** [comment]
I'm guessing that might be a real performance regression? Although is it comparing against `main` or `charlie/pycodestyle`? The latter includes the logical line rules, the former does not. I'll have to benchmark manually.

File: crates/ruff/src/rules/pycodestyle/rules/logical_lines/mod.rs (hunk 1 above)
Comment (MichaReiser) [reply crates/ruff/src/rules/pycodestyle/rules/logical_lines/mod.rs:119]: Should we fix this in the lexer instead? It feels odd that the newline is conditional on the comment placement. I would expect that a comment is always followed by a newline.

Nit. You can match directly on the Tok. Using TokenKind has some overhead that is only worth it when there are many reads.

Comment (charliermarsh) [reply crates/ruff/src/rules/pycodestyle/rules/logical_lines/mod.rs:119]: Honestly not sure. \cc @youknowone - do you know, if it's intentional that we don't emit a newline when a comment is at start-of-line?

Comment (charliermarsh) [reply crates/ruff/src/rules/pycodestyle/rules/logical_lines/mod.rs:119]: It may not actually be a bug, I'd have to compare to CPython.

Comment (charliermarsh) [reply crates/ruff/src/rules/pycodestyle/rules/logical_lines/mod.rs:119]: It looks like CPython _does_ emit a non-logical newline, even for entirely empty lines, unlike RustPython.

RustPython also has this test:

```rust
#[test]
fn test_logical_newline_line_comment() {
    let source = "#Hello\n#World";
    let tokens = lex_source(source);
    assert_eq!(
        tokens,
        vec![
            Tok::Comment("#Hello".to_owned()),
            // tokenize.py does put an NL here...
            Tok::Comment("#World".to_owned()),
            // ... and here, but doesn't seem very useful.
        ]
    );
}
```

@youknowone - Do you know if this is intentional, or should I fix it?

Comment (charliermarsh) [reply crates/ruff/src/rules/pycodestyle/rules/logical_lines/mod.rs:119]: Put up https://github.com/RustPython/Parser/pull/27. (We'll still need code changes here to fix this bug, once that merges.)

Comment (MichaReiser) [reply crates/ruff/src/rules/pycodestyle/rules/logical_lines/mod.rs:119]: Thank you! Makes sense. Is the change to remove the explicit `Comment` handling and only rely on the presence of `Newline` and `NonLogicalNewline`?

**Review by MichaReiser — APPROVED** [review]

**Comment by MichaReiser** [comment]
> I'm guessing that might be a real performance regression? Although is it comparing against `main` or `charlie/pycodestyle`? The latter includes the logical line rules, the former does not. I'll have to benchmark manually.

I think it compares against `main`.

File: crates/ruff/src/rules/pycodestyle/rules/logical_lines/mod.rs (hunk 1 above)
Comment (youknowone) [reply crates/ruff/src/rules/pycodestyle/rules/logical_lines/mod.rs:119]: Thank you! I don't think RustPython intended to have different behavior to CPython.
I will look in the patch.

**Comment by charliermarsh** [comment]
Ugh this got confused.
