### PR TITLE
Exclude function definition from too-many-statements rule

### LINKED ISSUE #4659: Unexpected number of statements(PLR0915 Too many statements)
## Ruff Version
**ruff 0.0.269**
## Command(Powershell)
```powershell
ruff check --isolated --extend-select=PLR  .\main.py
```
## Output
```powershell
main.py:1:5: PLR0915 Too many statements (51 > 50)
Found 1 error.
```
## Source
**Please change the file extension from txt to py**
[main.txt](https://github.com/charliermarsh/ruff/files/11567206/main.txt)

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Pylint seems to include the `def` itself when counting the number of statements in a function, which feels off-by-one in practice. This PR removes that extra statement from the count.

Closes #4659.

### CODE REVIEW

File: crates/ruff/src/rules/pylint/rules/too_many_statements.rs [hunk 1]
```diff
@@ -176,7 +176,7 @@ mod tests {
     #[test]
     fn pass() -> Result<()> {
         let source: &str = r#"
-def f():  # 2
```
Comment (charliermarsh) [inline crates/ruff/src/rules/pylint/rules/too_many_statements.rs:179]: (These are redundant, we already include them in the `assert_equal!` below.)

File: crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__max_statements.snap [hunk 2]
```diff
@@ -1,28 +1,12 @@
 ---
 source: crates/ruff/src/rules/pylint/mod.rs
 ---
-too_many_statements_params.py:2:5: PLR0915 Too many statements (2 > 1)
-  |
-2 | # Too may statements (2/1) for max_statements=1
-3 | def f(x):
-  |     ^ PLR0915
-4 |     pass
```
Comment (charliermarsh) [inline crates/ruff/src/rules/pylint/snapshots/ruff__rules__pylint__tests__max_statements.snap:9]: E.g., it's strange that this fails with `max_statements=1`.
