### PR TITLE
Respect parent-scoping rules for `NamedExpr` assignments

### LINKED ISSUE #3997: Fails with assignment expression used in "any()" function
Content of "test.py":
```python
if any((key := x) for x in ["ok"]):
    print(key)
```
Ruff command:
```
ruff --isolated test.py
```

Ruff output:
```
test.py:2:11: F821 Undefined name `key`
```

Ruff version: 0.0.261

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Per [PEP 572](https://peps.python.org/pep-0572/#scope-of-the-target), a named expression assignment within a generator or comprehension actually binds to the parent scope. This is useful as it enables patterns like:

```py
# Compute partial sums in a list comprehension
total = 0
partial_sums = [total := total + v for v in values]
print("Total:", total)
```

Previously, we bound the named expression within the generator or comprehension, which led to us flagging `key` as undefined here:

```py
if any((key := x) for x in ["ok"]):
    print(key)
```

Closes #3997.

### CODE REVIEW

File: crates/ruff/src/checkers/ast/mod.rs [hunk 1]
```diff
@@ -4269,7 +4269,20 @@ impl<'a> Checker<'a> {
             }
         }
 
-        let scope = self.ctx.scope();
+        // Per [PEP 572](https://peps.python.org/pep-0572/#scope-of-the-target), named
+        // expressions in generators and comprehensions bind to the parent scope.
+        let scope_id = if binding.kind.is_named_expr_assignment() {
```
Comment (MichaReiser) [inline crates/ruff/src/checkers/ast/mod.rs:4274]: Nit: Would it make sense to return the `scope` instead
```suggestion
        let scope = if binding.kind.is_named_expr_assignment() {
```

It would avoid retrieving the id from the ancestor scope only to look it up again.

**Review by MichaReiser — APPROVED** [review]

File: crates/ruff/src/checkers/ast/mod.rs (hunk 1 above)
Comment (charliermarsh) [reply crates/ruff/src/checkers/ast/mod.rs:4274]: Yeah, it has to be `mut` though. I'll try to get it working.
