### PR TITLE
Do not autofix `E731` in class bodies

### LINKED ISSUE #3046: `E731` autofix broken for class vars
(`E731` is "do not assign a `lambda` expression, use a `def`")

Consider this example where a `dataclass` has a `Callable` attribute with a default value:

```python
from collections.abc import Callable
from dataclasses import dataclass

@dataclass
class Foo:
    bar: Callable[[], str] = lambda: "foo"
```

Ruff identifies the class variable assignment as a violation of `E731`:

```console
$ ruff check test.py --isolated
test.py:7:5: E731 [*] Do not assign a `lambda` expression, use a `def`
Found 1 error.
[*] 1 potentially fixable with the --fix option.
```

But the autofix transforms it into:

```python
from dataclasses import dataclass

@dataclass
class Foo:
    def bar():
        return "foo"
```

which is not equivalent. 

Looking at https://github.com/charliermarsh/ruff/blob/9168a12679976ece5e94dd9cf6abe3c8886e31cc/crates/ruff/src/rules/pycodestyle/rules/lambda_assignment.rs#L29-L37 it seems like the problem is that there's no check on whether it makes sense to do this transformation in the surrounding context (in this case, the autofix doesn't apply because we're in a `@dataclass` body, but maybe there are other contexts too?). 

I think the desired autofix in this case would be more like:

```python
from collections.abc import Callable
from dataclasses import dataclass

def bar():
    return "foo"

@dataclass
class Foo:
    bar: Callable[[], str] = bar
```

but that is only correct for dataclasses because we care about the type-annotated class variable! If this wasn't a dataclass, the original autofix would be fine and produces equivalent behavior at runtime. I'd suggest that as a first pass, there's just no autofix for `E731` if it occurs in a class body, because it depends on this question of whether the type-annotated class variable needs to exist for some other code to use, which is probably impossible to determine (since it's not just `@dataclass` that might use those annotations).

Happy to take a look at a fix for this issue myself, but I'm a first-time contributor so it might take some time :)

### PR DESCRIPTION
**Pull request by JoshKarpel**
Resolves #3046 

I tried to mirror how other not-always-fixable violations work, and I also tried to flatten out the conditional around the autofix itself.

### CODE REVIEW

File: crates/ruff/src/rules/pycodestyle/rules/lambda_assignment.rs [hunk 1]
```diff
@@ -2,64 +2,88 @@ use ruff_macros::{define_violation, derive_message_formats};
...
-    fn autofix_title(&self) -> String {
-        let LambdaAssignment(name) = self;
-        format!("Rewrite `{name}` as a `def`")
+    fn autofix_title_formatter(&self) -> Option<fn(&Self) -> String> {
+        let LambdaAssignment { fixable, .. } = self;
+        if *fixable {
+            Some(|v| format!("Rewrite `{}` as a `def`", v.name))
+        } else {
+            None
+        }
```
Comment (youknowone) [inline crates/ruff/src/rules/pycodestyle/rules/lambda_assignment.rs:33]: maybe you like this form
```suggestion
        self.fixable
            .then_some(|v| format!("Rewrite `{}` as a `def`", v.name))
```

Comment (JoshKarpel) [reply crates/ruff/src/rules/pycodestyle/rules/lambda_assignment.rs:33]: I do!

**Comment by charliermarsh** [comment]
Looks great, no notes -- thank you so much!
