### PR TITLE
Handle `UP032` autofix with adjacent keywords

### LINKED ISSUE #3627: [Autofix error] Fails to fix file which formats output
Ruff  a45753f462c7a53afd7f942ab3c6f9af3871bf1f

```
class AbstractFolderIO:
    def __repr__(self):
        return'<%s: %s>' % (self.__class__.__name__, self.path)
```
with 
```
ruff file.py --fix
```

```
error: Autofix introduced a syntax error. Reverting all changes.

This indicates a bug in `ruff`. If you could open an issue at:

    https://github.com/charliermarsh/ruff/issues/new?title=%5BAutofix%20error%5D

...quoting the contents of `Desktop/RunEveryCommand/Ruff/Broken/23027file_io (3rd copy)0.py`, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!

Desktop/RunEveryCommand/Ruff/Broken/23027file_io (3rd copy)0.py:1:1: INP001 File `Desktop/RunEveryCommand/Ruff/Broken/23027file_io (3rd copy)0.py` is part of an implicit namespace package. Add an `__init__.py`.
Desktop/RunEveryCommand/Ruff/Broken/23027file_io (3rd copy)0.py:1:1: D100 Missing docstring in public module
Desktop/RunEveryCommand/Ruff/Broken/23027file_io (3rd copy)0.py:1:7: D101 Missing docstring in public class
Desktop/RunEveryCommand/Ruff/Broken/23027file_io (3rd copy)0.py:2:9: ANN204 Missing return type annotation for special method `__repr__`
Desktop/RunEveryCommand/Ruff/Broken/23027file_io (3rd copy)0.py:2:9: D105 Missing docstring in magic method
Desktop/RunEveryCommand/Ruff/Broken/23027file_io (3rd copy)0.py:2:18: ANN101 Missing type annotation for `self` in method
Desktop/RunEveryCommand/Ruff/Broken/23027file_io (3rd copy)0.py:3:15: Q000 Single quotes found but double quotes preferred
Desktop/RunEveryCommand/Ruff/Broken/23027file_io (3rd copy)0.py:3:15: UP031 Use format specifiers instead of percent format

```

### PR DESCRIPTION
**Pull request by JonathanPlasse**
- Close #3627

### CODE REVIEW

File: crates/ruff/src/rules/pyupgrade/rules/f_strings.rs [hunk 1]
```diff
@@ -247,17 +247,33 @@ pub(crate) fn f_strings(checker: &mut Checker, summary: &FormatSummary, expr: &E
...
+    } else {
+        let existing = checker.locator.slice(Range::new(
+            expr_range.location.with_col_offset(-1),
+            expr_range.end_location,
+        ));
+        if contents.len() > existing.len() - 1 {
+            return;
+        }
+        // Add a space if there is none between a keyword and the string.
+        // `return`, `yield`, `assert`, …
```
Comment (charliermarsh) [inline crates/ruff/src/rules/pyupgrade/rules/f_strings.rs:270]: There might be more cases to consider here -- I haven't really thought it through rigorously... But for example, `rf"{expr}"` is valid.

Comment (charliermarsh) [reply crates/ruff/src/rules/pyupgrade/rules/f_strings.rs:270]: But I don't think we can _just_ check `r`, because some keywords end in `r`.

Comment (JonathanPlasse) [reply crates/ruff/src/rules/pyupgrade/rules/f_strings.rs:270]: `rf"{expr}"` is inside the range of the expression, it the character before the expression that is looked at, not `r` from the string.
Also it is not possible to have `r` before the string in this case as it would be a syntax error `returnr"foo"`.

Comment (JonathanPlasse) [reply crates/ruff/src/rules/pyupgrade/rules/f_strings.rs:270]: There is also `and`, `or`, `not`, ...
That is why I used `is_ascii_alphabetic`.

Comment (charliermarsh) [reply crates/ruff/src/rules/pyupgrade/rules/f_strings.rs:270]: Ahh right right.

And this is valid, right?

```py
return\
f"foo"
```

Comment (JonathanPlasse) [reply crates/ruff/src/rules/pyupgrade/rules/f_strings.rs:270]:
```python
def f():
    return\
"{}".format(1)
```
becomes
```python
def f():
    return\
f"{1}"
```
