### PR TITLE
Add `Applicability` to `Fix`

### LINKED ISSUE #4183: Add `Applicability` to `Fix`
Part of #4181 and depends on #4182

* Add a new `Applicability` enum in `fix.rs` similar to [Rome's](https://github.com/rome/tools/blob/38104b339da8ff688f469799e1fc3f4a46f3d2ec/crates/rome_diagnostics/src/suggestion.rs#L6-L16) or [Clippy's](https://doc.rust-lang.org/stable/nightly-rustc/rustc_errors/enum.Applicability.html) `Applicability` enums with three variants: 
	* `Safe` (or `Automatic`, `Always`, `MachineApplicable`?)
	* `MaybeIncorrect`
	* `Unspecified`
* Add the `applicability` field to `Fix`
* Add the new `safe` and `safe_edits` constructor functions (identical to `unspecified` and `unspecified_edits)`
* Add the new `maybe_incorrect` and `maybe_incorrect_edits` constructor functions (identical to `unspecified` and `unspecified_edits)`
* Mark `unspecified` and `unspecified_edits` as `deprecated` (new lints should use either `safe_*` or `maybe_incorrect_*). Add `allow(deprecated)` at the call-sites. 
* Change the [`Diff`](https://github.com/charliermarsh/ruff/blob/fdd5fd2ad1999ef43a418da29f37858fd98cb151/crates/ruff/src/message/diff.rs#L54) implementation to write `Suggested Fix` for `MaybeIncorrect` and `Unspecified`, and `Safe fix` for `Applicability::Safe`.

### PR DESCRIPTION
**Pull request by madkinsz**
Adds `Applicability` levels to `Fix` with corresponding factory methods and deprecates the `unspecified` fix methods.

Updates `Diff` output to include "Fix", "Suggested fix", and "Possible fix" depending on the applicability. 

Closes #4183

### CODE REVIEW

File: crates/ruff_diagnostics/src/fix.rs [hunk 1]
```diff
@@ -4,23 +4,106 @@ use serde::{Deserialize, Serialize};
 
 use crate::edit::Edit;
 
+/// Indicates confidence in the correctness of a suggested fix.
+#[derive(Default, Copy, Clone, Debug, Hash, PartialEq, Eq, PartialOrd, Ord)]
+#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
+#[non_exhaustive]
+pub enum Applicability {
```
Comment (madkinsz) [inline crates/ruff_diagnostics/src/fix.rs:11]: I think this may actually be exhaustive with these members; should I drop the `non_exhaustive`?

File: crates/ruff/src/message/diff.rs [hunk 2]
```diff
@@ -47,8 +47,14 @@ impl Display for Diff<'_> {
 
         let diff = TextDiff::from_lines(self.source_code.source_text(), &output);
 
-        writeln!(f, "{}", "ℹ Suggested fix".blue())?;
-
+        let message = match self.fix.applicability() {
+            Applicability::Automatic => "Fix",
+            Applicability::Suggested => "Suggested fix",
+            Applicability::Manual => "Possible fix",
+            _ => "Suggested fix",  // For backwards compatibility, unspecified fixes are 'suggested'
```
Comment (madkinsz) [inline crates/ruff/src/message/diff.rs:54]: I think we can change this case to explicitly cover only `Unspecified` if we drop the non-exhaustive from the enum https://github.com/charliermarsh/ruff/pull/4303/files#r1188177338

File: crates/ruff/src/message/diff.rs [hunk 3]
```diff
@@ -47,8 +47,14 @@ impl Display for Diff<'_> {
 
         let diff = TextDiff::from_lines(self.source_code.source_text(), &output);
 
-        writeln!(f, "{}", "ℹ Suggested fix".blue())?;
-
+        let message = match self.fix.applicability() {
+            Applicability::Automatic => "Fix",
```
Comment (MichaReiser) [inline crates/ruff/src/message/diff.rs:51]: Nit: What would you think of "Safe fix" (I'm undecided, Fix is short and to the point)?

File: crates/ruff/src/rules/flake8_pie/rules.rs [hunk 4]
```diff
@@ -136,6 +136,8 @@ pub fn no_unnecessary_pass(checker: &mut Checker, body: &[Stmt]) {
                 let mut diagnostic = Diagnostic::new(UnnecessaryPass, pass_stmt.range());
                 if checker.patch(diagnostic.kind.rule()) {
                     if let Some(index) = trailing_comment_start_offset(pass_stmt, checker.locator) {
+                        #[allow(deprecated)]
+                        #[allow(deprecated)]
```
Comment (MichaReiser) [inline crates/ruff/src/rules/flake8_pie/rules.rs:140]:
```suggestion
```

File: crates/ruff/src/rules/flake8_pytest_style/rules/assertion.rs [hunk 5]
```diff
@@ -204,6 +204,8 @@ pub fn unittest_assertion(
                 );
                 if fixable && checker.patch(diagnostic.kind.rule()) {
                     if let Ok(stmt) = unittest_assert.generate_assert(args, keywords) {
+                        #[allow(deprecated)]
+                        #[allow(deprecated)]
```
Comment (MichaReiser) [inline crates/ruff/src/rules/flake8_pytest_style/rules/assertion.rs:208]:
```suggestion
```

File: crates/ruff/src/rules/pyupgrade/rules/native_literals.rs [hunk 6]
```diff
@@ -64,7 +64,8 @@ pub fn native_literals(
                 LiteralType::Bytes
             }}, expr.range());
             if checker.patch(diagnostic.kind.rule()) {
-                diagnostic.set_fix(Fix::unspecified(Edit::range_replacement(
+                #[allow(deprecated)]
+diagnostic.set_fix(Fix::unspecified(Edit::range_replacement(
```
Comment (MichaReiser) [inline crates/ruff/src/rules/pyupgrade/rules/native_literals.rs:68]: The intention looks off, but all good if `rustfmt` is happy.

File: crates/ruff_diagnostics/src/fix.rs (hunk 1 above)
Comment (MichaReiser) [reply crates/ruff_diagnostics/src/fix.rs:11]: I think dropping `non_exhaustive` should be fine for now because we don't provide a Rust API, meaning we are in control of all usages and can adopt then when extending the enum.

File: crates/ruff_diagnostics/src/fix.rs [hunk 7]
```diff
@@ -4,23 +4,106 @@ use serde::{Deserialize, Serialize};
...
+        note = "Use `Fix::automatic_edits`, `Fix::suggested_edits`, or `Fix::manual_edits` instead to specify an applicability."
+    )]
     pub fn unspecified_edits(edit: Edit, rest: impl IntoIterator<Item = Edit>) -> Self {
         Self {
             edits: std::iter::once(edit).chain(rest.into_iter()).collect(),
+            applicability: Applicability::Unspecified,
+        }
+    }
+
+    /// Create a new [`Fix`] with automatic applicability from an [`Edit`] element.
```
Comment (MichaReiser) [inline crates/ruff_diagnostics/src/fix.rs:62]: I recommend repeating the `automatic` applicability documentation here. Most users will only use the `Fix` API, and explaining what `automatic` safes them a jump in the documentation (or make sure they read it).

```suggestion
    /// Create a new [`Fix`] with [automatic applicability](Applicability::Automatic) from an [`Edit`] element.
```

**Review by MichaReiser — APPROVED** [review]
Thank you so much! I hope adding all the `allow(deprecated)` wasn't too much pain?

File: crates/ruff/src/rules/flake8_pie/rules.rs (hunk 4 above)
Comment (madkinsz) [reply crates/ruff/src/rules/flake8_pie/rules.rs:140]: Thanks! I'll go through the diff once more too and make sure I got all these — I started manually then switched to a regex replace and ended up with some duplicates and weird formatting :)

File: crates/ruff/src/message/diff.rs (hunk 3 above)
Comment (madkinsz) [reply crates/ruff/src/message/diff.rs:51]: I'm unsure. It could also be "Automatic fix". I'm leaning towards brevity — it seems like an easy thing to change in the future if users are confused.

File: crates/ruff_diagnostics/src/fix.rs (hunk 7 above)
Comment (madkinsz) [reply crates/ruff_diagnostics/src/fix.rs]: 👍 did this for all of the levels
