### PR TITLE
Track symbol deletions separately from bindings

### LINKED ISSUE #4746: PLE0117 - nonlocal name found without binding - false possitive
- version - 0.0.270
- command `ruff .`
- no especially relevant settings

It seems that [`PLE0117`](https://beta.ruff.rs/docs/rules/nonlocal-without-binding/) erroneously considers `del` statements when determining if a variable as been assigned

```python
def f():
    x = 1

    def g():
        nonlocal x  # error: PLE0117
        x = 2

    del x
```

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

#4746 revealed some subtle issues related to Python's handling of `nonlocal`. If you use `nonlocal`, and the non-local symbol isn't declared in the parent scope, Python raises a syntax error at parse time (!). However, I didn't realize that, for the purpose of declarations, Python will respect a `del` statement -- so this works fine:

```py
def f():
    def g():
        nonlocal x

    del x
```

Previously, to determine whether the symbol was declared in the parent scope, we checked if the symbol was _bound_ in the parent scope. But we don't create bindings for deletions, and in fact, we remove any existing bindings when we hit a deletion.

This PR thus modifies `Scope` to track all deleted symbols, so that we can ask the scope whether the symbol should be considered "declared" for the purpose of `nonlocal` analysis.

Closes #4746.

### CODE REVIEW

File: crates/ruff_python_semantic/src/scope.rs [hunk 1]
```diff
@@ -23,6 +23,8 @@ pub struct Scope<'a> {
     bindings: FxHashMap<&'a str, BindingId>,
     /// A map from binding ID to binding ID that it shadows.
     shadowed_bindings: HashMap<BindingId, BindingId, BuildNoHashHasher<BindingId>>,
+    /// A list of all names declared in the scope.
+    declared_symbols: Vec<&'a str>,
```
Comment (charliermarsh) [inline crates/ruff_python_semantic/src/scope.rs:27]: This might be a bit of a heavy-handed change just to fix this one semantic issue... E.g., we could instead track `deleted_names`, and make `declares` something like `self.has(name) || self.deletions.contains(name)`.

Comment (charliermarsh) [reply crates/ruff_python_semantic/src/scope.rs:27]: (We could also track `HashMap<&'a str, SymbolId>`, and make `bindings: FxHashMap<SymbolId, BindingId>`.)

Comment (Boshen) [reply crates/ruff_python_semantic/src/scope.rs]: I'm having a hard time comprehending the difference between a `declared_symbol` vs a `binding` based on their names and comments alone 🤯

**Review by konstin — APPROVED** [review]

File: crates/ruff_python_semantic/src/scope.rs (hunk 1 above)
Comment (charliermarsh) [reply crates/ruff_python_semantic/src/scope.rs]: I'm going to rewrite this to special-case deletions. I need to reconsider deletions more holistically.

File: crates/ruff_python_semantic/src/scope.rs [hunk 2]
```diff
@@ -19,6 +19,8 @@ pub struct Scope<'a> {
     /// A list of star imports in this scope. These represent _module_ imports (e.g., `sys` in
     /// `from sys import *`), rather than individual bindings (e.g., individual members in `sys`).
     star_imports: Vec<StarImportation<'a>>,
+    /// A list of all names declared in the scope.
+    declared_symbols: Vec<&'a str>,
```
Comment (MichaReiser) [inline crates/ruff_python_semantic/src/scope.rs:23]: Would it make sense to instead track deleted `symbol`s, considering that deletions are rare (so that the vec is empty 99% of the cases)?

Comment (charliermarsh) [reply crates/ruff_python_semantic/src/scope.rs:23]: Yes, I did that initially. I'm going to revert to that state.

File: crates/ruff_python_semantic/src/scope.rs [hunk 3]
```diff
@@ -19,6 +19,8 @@ pub struct Scope<'a> {
...
     /// A map from bound name to binding ID.
     bindings: FxHashMap<&'a str, BindingId>,
```
[the remark this answers is not in the document]
Comment (charliermarsh) [reply crates/ruff_python_semantic/src/scope.rs:25]: This is defined on the relevant method docstrings (`declares` vs. `has`).

File: crates/ruff_python_semantic/src/scope.rs [hunk 4]
```diff
@@ -63,18 +67,28 @@ impl<'a> Scope<'a> {
...
             None
         }
     }
 
-    /// Returns `true` if this scope defines a binding with the given name.
-    pub fn defines(&self, name: &str) -> bool {
+    /// Removes the binding with the given name.
+    pub fn delete(&mut self, name: &'a str) -> Option<BindingId> {
+        self.declared_symbols.push(name);
+        self.bindings.remove(name)
```
[the remark this answers is not in the document]
Comment (charliermarsh) [reply crates/ruff_python_semantic/src/scope.rs:78]: This actually isn't sufficient, because this needs to be considered valid (for the purpose of the `nonlocal` rule):

```py
def f():
    del x

    def g():
        nonlocal x
```

`del x` adds `x` to the symbol table, but doesn't bind it to the value (or something like that -- I don't have the terminology nailed down).
