### PR TITLE
Include individual path checks in --verbose logging

### LINKED ISSUE #3423: Add ability to check files one by one and print which are currently checked/parsed
When trying to found file which crashes, I use binary search so I:
1. run ruff to check for crash
2. remove half of files
3. run again to see if crash still happens
4. if yes, back to point 2
5. if no, restore half of files, remove other part, back to point 3

With such output I will be able to find crash with seconds instead minutes(of course this should work only on 1 thread):
```
[[ Parsing a.py ]]
[[ Parsing b.py ]]
[[ Parsing c.py ]]
[[ Parsing d.py ]]

[[ Checking a.py file ]]
a.py:21:9: D400 [*] First line should end with a period
[[ Checking a.py file ]]
b.py:21:9: D415 [*] First line should end with a period, question mark, or exclamation point
[[ Checking c.py file ]]
[[ Checking d.py file ]]
```

### PR DESCRIPTION
**Pull request by charliermarsh**
This modifies `ruff /path/to/file.py --verbose` to include a message for each file that's checked. `--verbose` is, in truth, more like `--debug`, but this generally fits with what we include in verbose logging.

Closes #3423.

### CODE REVIEW

File: crates/ruff/src/resolver.rs [hunk 1]
```diff
@@ -128,7 +128,7 @@ pub fn resolve_configuration(
 
         // Resolve the current path.
         let options = pyproject::load_options(&path)
-            .map_err(|err| anyhow!("Failed to parse `{}`: {}", path.to_string_lossy(), err))?;
+            .map_err(|err| anyhow!("Failed to parse `{}`: {}", path.display(), err))?;
```
Comment (charliermarsh) [inline crates/ruff/src/resolver.rs:131]: Separately: pretty sure we want to be using `.display` when constructing user-facing paths?

**Review by MichaReiser — APPROVED** [review]
Does the logging add any noticeable performance penalty?

**Comment by charliermarsh** [comment]
When running with `--verbose`, or without?

**Comment by MichaReiser** [comment]
Mainly without. I'm not really concerned about performance when using verbose.

**Comment by charliermarsh** [comment]
It does seem noticeably slower by a few ms (on a ~214ms baseline). I don't understand why or how though. Doesn't `path.display()` only execute when the log level is set to debug or higher?

**Comment by charliermarsh** [comment]
Hmm, actually, this just looks like noise. I need a more reliable benchmark.
