### PR TITLE
Fix TRY300 false positive

### LINKED ISSUE #3632: False positive `TRY300` when there is no `except` clause
In napari we have such a function https://github.com/napari/napari/blob/ab885957fb5a2220a3078851ad7dc97a7a82cc05/napari/utils/misc.py#L253

```python
def formatdoc(obj):
    """Substitute globals and locals into an object's docstring."""
    frame = inspect.currentframe().f_back
    try:
        obj.__doc__ = obj.__doc__.format(
            **{**frame.f_globals, **frame.f_locals}
        )
        return obj
    finally:
        del frame
```

The `TRY300` is reported on `return obj`. But the else clause is available only when the `except` clause is present (there needs to be at least one). So `TRY300` should not be reported if there is no except clause. Or it should have different text describing that. 

Currently:

```
TRY300 Consider moving this statement to an `else` block
```

Possible:

```
TRY300 Consider moving this statement after `try: finally:`
```

### PR DESCRIPTION
**Pull request by JonathanPlasse**
- Close #3632

### CODE REVIEW

File: crates/ruff/src/rules/tryceratops/rules/try_consider_else.rs [hunk 1]
```diff
@@ -17,8 +17,8 @@ impl Violation for TryConsiderElse {
 }
 
 /// TRY300
-pub fn try_consider_else(checker: &mut Checker, body: &[Stmt], orelse: &[Stmt]) {
-    if body.len() > 1 && orelse.is_empty() {
+pub fn try_consider_else(checker: &mut Checker, body: &[Stmt], orelse: &[Stmt], has_handler: bool) {
```
Comment (charliermarsh) [inline crates/ruff/src/rules/tryceratops/rules/try_consider_else.rs:20]: Nit: let's pass `handlers`, so that the arguments here roughly match the "shape" of the AST node (and the n check `handlers.is_empty()` in here.

Comment (JonathanPlasse) [reply crates/ruff/src/rules/tryceratops/rules/try_consider_else.rs]: Done.
