### PR TITLE
isort: fix bad interaction between `force-sort-within-sections` and `force-to-top`

### LINKED ISSUE #3630: isort: bad interaction between `force-sort-within-sections` and `force-to-top`
Given this config:

```toml
[tool.isort]
force_to_top = ["typing"]
force_sort_within_sections = true

[tool.ruff]
select = ["I001"]
[tool.ruff.isort]
force-to-top = ["typing"]
force-sort-within-sections = true
```

and this isort-clean file:

```py
from typing import Any
import abc
from abc import ABCMeta
import os
```

ruff fix gives:

```py
import abc
import os
from typing import Any
from abc import ABCMeta
```

It looks like `force-sort-within-sections` (which says to not sort the `import`s and `from`s separately) is ignored. But if I comment out the `force-to-top = ["typing"]` setting, ruff gives:

```py
import abc
from abc import ABCMeta
import os
from typing import Any
```

which is correct. So I'm guessing the two settings together cause the issue.

(I'll try to fix this issue when I get a chance, unless someone beats me to it)

Version: ruff 0.0.257

### PR DESCRIPTION
**Pull request by bluetech**
Fixes #3630.

To ease review I split to 2 commits - simple refactor + the logic change.

I've tested this on our code base, works well now.

### CODE REVIEW

File: crates/ruff/src/rules/isort/sorting.rs [hunk 1]
```diff
@@ -44,29 +44,31 @@ fn prefix(
...
 }
 
+/// Compare two module names' "force-to-topness".
+fn cmp_force_to_top(name1: &str, name2: &str, force_to_top: &BTreeSet<String>) -> Ordering {
+    match (force_to_top.contains(name1), force_to_top.contains(name2)) {
+        (true, true) => Ordering::Equal,
+        (false, false) => Ordering::Equal,
+        (true, false) => Ordering::Less,
+        (false, true) => Ordering::Greater,
+    }
```
Comment (JonathanPlasse) [inline crates/ruff/src/rules/isort/sorting.rs:54]:
```suggestion
    force_to_top.contains(name2).cmp(force_to_top.contains(name1))
```

Comment (bluetech) [reply crates/ruff/src/rules/isort/sorting.rs]: Changed to something similar, thanks.
