### PR TITLE
Respect insertion location when importing symbols

### LINKED ISSUE #4208: [Linter panic] My File: torch\_inductor\select_algorithm.py
ruff version 0.0.264 (ruff --version)

## command(Powershell)
```powershell
ruff check --select=ALL --fix --isolated .\select_algorithm.py
```
The source is a Python file from PyTorch, but it is not the original file (with a different hash value).
The original file can be found at https://github.com/pytorch/pytorch/blob/8b64dee5d2e0e61c3c37a222c43b636d20cc58b7/torch/_inductor/select_algorithm.py
OS: Windows 11 22H2
## Terminal Content(include stack trace):
```powershell
warning: `one-blank-line-before-class` (D203) and `no-blank-line-before-class` (D211) are incompatible. Ignoring `one-blank-line-before-class`.
warning: `multi-line-summary-first-line` (D212) and `multi-line-summary-second-line` (D213) are incompatible. Ignoring `multi-line-summary-second-line`.
warning: Linting panicked select_algorithm.py: This indicates a bug in `ruff`. If you could open an issue at:

https://github.com/charliermarsh/ruff/issues/new?title=%5BLinter%20panic%5D

with the relevant file contents, the `pyproject.toml` settings, and the following stack trace, we'd be very appreciative!

panicked at 'assertion failed: start.raw <= end.raw', C:\Users\runneradmin\.cargo\git\checkouts\rustpython-80c0a11a8fa8e175\c3147d2\ruff_text_size\src\range.rs:48:9
Backtrace:    0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: BaseThreadInitThunk
  18: RtlUserThreadStart
  ```
  ## File Content(Python code):
**Please change the file extension from txt to py**
  [select_algorithm.txt](https://github.com/charliermarsh/ruff/files/11383334/select_algorithm.txt)
  ## pyproject.toml
```toml
[build-system]
requires = [
    "setuptools",
    "wheel",
    "astunparse",
    "numpy",
    "ninja",
    "pyyaml",
    "setuptools",
    "cmake",
    "typing-extensions",
    "requests",
]
# Use legacy backend to import local packages in setup.py
build-backend = "setuptools.build_meta:__legacy__"


[tool.black]
# Uncomment if pyproject.toml worked fine to ensure consistency with flake8
# line-length = 120
target-version = ["py38", "py39", "py310", "py311"]


[tool.ruff]
target-version = "py38"

# NOTE: Synchoronize the ignores with .flake8
ignore = [
    # these ignores are from flake8-bugbear; please fix!
    "B007", "B008", "B017",
    "B018", # Useless expression
    "B019", "B020",
    "B023", "B024", "B026",
    "B028", # No explicit `stacklevel` keyword argument found
    "B027", "B904", "B905",
    "E402",
    "C408", # C408 ignored because we like the dict keyword argument syntax
    "E501", # E501 is not flexible enough, we're using B950 instead
    "E721",
    "E731", # Assign lambda expression
    "E741",
    "EXE001",
    "F405",
    "F821",
    "F841",
    # these ignores are from flake8-logging-format; please fix!
    "G101", "G201", "G202",
    "SIM102", "SIM103", "SIM112", # flake8-simplify code styles
    "SIM105", # these ignores are from flake8-simplify. please fix or ignore with commented reason
    "SIM108",
    "SIM110",
    "SIM114", # Combine `if` branches using logical `or` operator
    "SIM115",
    "SIM116", # Disable Use a dictionary instead of consecutive `if` statements
    "SIM117",
    "SIM118",
]
line-length = 120
select = [
    "B",
    "C4",
    "G",
    "E",
    "F",
    "SIM1",
    "W",
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"torchgen/api/types/__init__.py" = [
    "F401",
    "F403",
]
"torchgen/executorch/api/types/__init__.py" = [
    "F401",
    "F403",
]
```

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Previously, `Importer` would only track the most recently-seen top-level import statement, and would add any new imports _after_ that statement. However, because we visit function bodies and other scopes in a deferred manner, then if there are top-level imports _below_ a given function, we'll visit those imports, then visit the function body, then insert the new import _after_ the function.

This causes two problems: (1) it breaks the invariant, enforced in the fixer, that edits are _ordered_, since the import insertion can come _after_ the edit that makes use of the symbol; and (2) in theory, this could lead to broken code, since a function could be called _before_ we reach the import statement (since that statement comes later in the module).

The fix here is to track all import statements, and return the last import statement _before_ a given edit location.

Closes #4208.

### CODE REVIEW

File: crates/ruff/src/importer.rs [hunk 1]
```diff
@@ -18,10 +17,7 @@ pub struct Importer<'a> {
     python_ast: &'a Suite,
     locator: &'a Locator<'a>,
     stylist: &'a Stylist<'a>,
-    /// A map from module name to top-level `StmtKind::ImportFrom` statements.
-    import_from_map: FxHashMap<&'a str, &'a Stmt>,
```
Comment (charliermarsh) [inline crates/ruff/src/importer.rs:22]: I opted to get rid of this and just do a full search. The number of imports is typically not huge, this operation is relatively rare, and we'd now have to track `FxHashMap<&'a str, Vec<&'a Stmt>>` anyway.

File: crates/ruff/src/importer.rs [hunk 2]
```diff
@@ -88,10 +71,30 @@ impl<'a> Importer<'a> {
...
-    /// Return the top-level [`Stmt`] that imports the given module using `StmtKind::ImportFrom`.
-    /// if it exists.
-    pub fn get_import_from(&self, module: &str) -> Option<&Stmt> {
-        self.import_from_map.get(module).copied()
+    /// Return the top-level [`Stmt`] that imports the given module using `StmtKind::ImportFrom`
+    /// preceding the given position, if any.
+    pub fn find_import_from(&self, module: &str, at: TextSize) -> Option<&Stmt> {
+        let idx = self
+            .ordered_imports
+            .partition_point(|stmt| stmt.start() < at);
```
Comment (charliermarsh) [inline crates/ruff/src/importer.rs:79]: Hard to reason about whether this preliminary search is worth it.

Comment (charliermarsh) [reply crates/ruff/src/importer.rs:79]: Probably not?

Comment (konstin) [reply crates/ruff/src/importer.rs:79]: If we assume that in most file all imports are at the start of the file, just `if stmt.start() > at { return false; }` in the find should be faster.

File: crates/ruff/src/rules/isort/rules/add_required_imports.rs [hunk 3]
```diff
@@ -120,7 +120,10 @@ fn add_required_import(
         TextRange::default(),
     );
     if autofix.into() && settings.rules.should_fix(Rule::MissingRequiredImport) {
-        diagnostic.set_fix(Importer::new(python_ast, locator, stylist).add_import(required_import));
+        diagnostic.set_fix(
+            Importer::new(python_ast, locator, stylist)
+                .add_import(required_import, TextSize::default()),
```
Comment (konstin) [inline crates/ruff/src/rules/isort/rules/add_required_imports.rs:125]: Shouldn't this use the location of the first non-import statement, or do they need to be inserted even before the other imports?

**Review by konstin — APPROVED** [review]

File: crates/ruff/src/rules/isort/rules/add_required_imports.rs (hunk 3 above)
Comment (charliermarsh) [reply crates/ruff/src/rules/isort/rules/add_required_imports.rs:125]: They should be inserted at the top of the file -- since it has to work with `__future__` imports.
