### PR TITLE
Trigger N818 when parent ends in Error or Exception

### LINKED ISSUE #783: N818 ErrorSuffixOnExceptionName should apply recursively to sub-subclasses of Exception
This triggers `N818 exception name 'Bar' should be named with an Error suffix` in pep8-naming but not in Ruff:

```python
class FooError(Exception):
    pass

class Bar(FooError):
    pass
```

pep8-naming checks this by [recursively searching](https://github.com/PyCQA/pep8-naming/blob/b3492eeede12a26d35c0ee9e6b9c37a7e5484bf6/src/pep8ext_naming.py#L283-L293) all ancestor classes, although it may be nearly as effective to just check whether an immediate parent class has a name ending in `Error`.

### PR DESCRIPTION
**Pull request by charliermarsh**
Resolves #783.

### CODE REVIEW

File: src/pep8_naming/checks.rs [hunk 1]
```diff
@@ -224,7 +224,7 @@ pub fn error_suffix_on_exception_name(
 ) -> Option<Check> {
     if bases.iter().any(|base| {
         if let ExprKind::Name { id, .. } = &base.node {
-            id == "Exception"
+            id.ends_with("Exception") || id.ends_with("Error")
```
Comment (andersk) [inline src/pep8_naming/checks.rs:227]: Do we want to exempt `BaseException`, maybe with `id == "Exception" || id.ends_with("Error")`?

Comment (charliermarsh) [reply src/pep8_naming/checks.rs:227]: https://github.com/charliermarsh/ruff/pull/798
