### PR TITLE
Use take-while to terminate on parse errors

### LINKED ISSUE #277: Infinite loop on unclosed parenthesis
If you run ruff on this file with an unclosed parenthesis:

```python
print(
```

it loops forever allocating several GB of memory per second. This regression was introduced by 38b19b78b737ee3f2c0f781fb14950f4d4a97326. The problem is that

https://github.com/charliermarsh/ruff/blob/886def13bd2cfc2bfb20ad3c0e42991f5ac1e2cb/src/linter.rs#L87

produces an infinite stream of `Err(LexicalError { error: Eof, location: Location { row: 2, column: 1 } })` repeating forever, which doesn’t fit easily into a `Vec`.

### PR DESCRIPTION
**Pull request by charliermarsh**
Resolves #277.

### CODE REVIEW

File: src/linter.rs [hunk 1]
```diff
@@ -84,10 +82,15 @@ pub fn lint_path(
     let contents = fs::read_file(path)?;
 
     // Tokenize once.
-    let tokens: Vec<LexResult> = lexer::make_tokenizer(&contents).collect();
+    let tokens: Vec<LexResult> = lexer::make_tokenizer(&contents)
+        .take_while(Result::is_ok)
+        .collect();
```
Comment (andersk) [inline src/linter.rs:87]: This discards any `Err` completely, which doesn’t seem like it should be right?

Comment (charliermarsh) [reply src/linter.rs:87]: We still get errors from the parser (e.g., `foo.py:1:7: E999 SyntaxError: Got unexpected EOF` when parsing `print(`), though you're probably right. Lemme iterate on it for a sec.
