### PR TITLE
add fixes for __future__ import removal

### LINKED ISSUE #312: Automatically remove __future__ imports
This may require adding target Python versions to the configuration settings.

Source: https://github.com/asottile/pyupgrade

Screen Shot 2022-10-03 at 6 19 54 PM

### PR DESCRIPTION
**Pull request by chammika-become**
This PR will close #312

- Added Fixes to remove detected imports
- Added more test fixtures
- Added `UnnecessaryFutureImports` to `fixable`
- Updated README

Detection/fix code is elevated to the `Stmt` level since some imports need to be fully removed. Earlier detection at `alias` level doesn't seem right for that. As suggested, fix code is heavily borrowed from `pyflakes::fixes::remove_unused_import_froms`, perhaps need to refactor in future to share code. 
One main thing to object to, is that fix code pretty much do the detection all over again.
@charliermarsh is there better way to share detection results for fix purposes other than to display messages ?

### CODE REVIEW

File: src/checks.rs [hunk 1]
```diff
@@ -1466,8 +1466,8 @@ impl CheckKind {
             CheckKind::SuperCallWithParameters => {
                 "Use `super()` instead of `super(__class__, self)`".to_string()
             }
-            CheckKind::UnnecessaryFutureImport(name) => {
-                format!("Unnessary __future__ import `{name}` for target Python version")
+            CheckKind::UnnecessaryFutureImports(name) => {
```
Comment (charliermarsh) [inline src/checks.rs:1469]: Nit: can we make this `names` and take a vector, rather than a pre-formatted string? Then we can split the check to have proper pluralization, like:

```rust
CheckKind::DuplicateHandlerException(names) => {
    if names.len() == 1 {
        let name = &names[0];
        format!("Exception handler with duplicate exception: `{name}`")
    } else {
        let names = names.iter().map(|name| format!("`{name}`")).join(", ");
        format!("Exception handler with duplicate exceptions: {names}")
    }
}
```

(Using a vector as the argument, rather than a pre-formatted string, will also yield a nicer fixture file, since the list of names will be structured data rather than a comma-joined string.)

File: src/pyupgrade/fixes.rs [hunk 2]
```diff
@@ -133,6 +137,78 @@ pub fn remove_super_arguments(locator: &SourceCodeLocator, expr: &Expr) -> Optio
...
+            let name = &alias.node.name.as_str();
+            if (version >= PythonVersion::Py33 && PY33_PLUS_REMOVE_FUTURES.contains(name))
+                || (version >= PythonVersion::Py37 && PY37_PLUS_REMOVE_FUTURES.contains(name))
+            {
+                Some(index)
+            } else {
+                None
+            }
+        })
+        .collect::<Vec<_>>();
```
Comment (charliermarsh) [inline src/pyupgrade/fixes.rs:187]: I know you mentioned this in the PR summary, but we should try to avoid having this logic in two places (right now it's here, but also in `pyupgrade/checks.rs`).

How bout we remove `pyupgrade/checks.rs`, move the detection logic into `pyupgrade/plugins/unnecessary_future_import.rs` directly, and then pass in the list of names to remove as an argument to this function directly?

File: src/pyupgrade/fixes.rs [hunk 3]
```diff
@@ -133,6 +137,78 @@ pub fn remove_super_arguments(locator: &SourceCodeLocator, expr: &Expr) -> Optio
...
+    for index in removable.iter().rev() {
+        aliases.remove(*index);
+    }
+
+    if let Some(alias) = aliases.last_mut() {
+        alias.comma = trailing_comma;
+    }
+
+    if aliases.is_empty() {
+        autofix::helpers::remove_stmt(stmt, None, &[])
```
Comment (charliermarsh) [inline src/pyupgrade/fixes.rs:199]: We do need to pass in `parent` and `deleted` here, as in `remove_unused_import_froms`.

**Review by charliermarsh — COMMENTED** [review]
Great! Some feedback below.

File: src/pyupgrade/fixes.rs (hunk 2 above)
Comment (chammika-become) [reply src/pyupgrade/fixes.rs]: Make sense. Removed from `checks` and moved to the `plugins`

File: src/pyupgrade/fixes.rs (hunk 3 above)
Comment (chammika-become) [reply src/pyupgrade/fixes.rs]: Got the `deleted`, I am at lost about how to get the `parent`

Comment (charliermarsh) [reply src/pyupgrade/fixes.rs]: All good, I’ll take a look and fix before merging :)
