### PR TITLE
Avoid removing comment hash for noqa's with trailing content

### LINKED ISSUE #3586: [Autofix] Autofix fails with docstring
Ruff 1dd3cbd047beda01a7833e1b20e10e745757fe3e + PR #3584
No config
```
ruff . --fix
```
on
```
class MeasurementSchemaUpdateRequest(object):
    def columns(self, columns):
        """Set the columns of this MeasurementSchemaUpdateRequest.

        An ordered collection of column definitions
        """  # noqa: E򉷸01
```
cause error
```
error: Autofix introduced a syntax error. Reverting all changes.

This indicates a bug in `ruff`. If you could open an issue at:

    https://github.com/charliermarsh/ruff/issues/new?title=%5BAutofix%20error%5D

...quoting the contents of `/home/rafal/Desktop/RunEveryCommand/Ruff/Broken/50790measurement_schema_update_request0.py`, along with the `pyproject.toml` settings and executed command, we'd be very appreciative!
```

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

Right now, if you have a comment like `# noqa bar`, then when removing the blanket `# noqa`, we leave `bar` behind -- which is a syntax error.

It if the comment that trails the `noqa` is not itself a "partial comment" (like `# noqa # bar`), then we need to shift the deletion to _exclude_ the `#`.

Closes #3586.

### CODE REVIEW

File: crates/ruff/src/checkers/noqa.rs [hunk 1]
```diff
@@ -161,11 +161,16 @@ pub fn check_noqa(
                                     Location::new(row + 1, start - leading_spaces),
                                     Location::new(row + 1, end + trailing_spaces),
                                 ));
-                            } else {
+                            } else if lines[row].chars().nth(end + 1).map_or(false, |c| c == '#') {
```
Comment (MichaReiser) [inline crates/ruff/src/checkers/noqa.rs:164]: Let's use `skip_while(char::is_whitespace)` or call `lines[row][end...].trim_start()` to handle  `# noqua     # comment` correctly.


Can you also add a test case for it.

File: crates/ruff/src/checkers/noqa.rs [hunk 2]
```diff
@@ -161,11 +161,16 @@ pub fn check_noqa(
...
                                 diagnostic.amend(Fix::deletion(
                                     Location::new(row + 1, start),
                                     Location::new(row + 1, end + trailing_spaces),
                                 ));
+                            } else {
+                                diagnostic.amend(Fix::deletion(
+                                    Location::new(row + 1, start + 1),
+                                    Location::new(row + 1, end),
+                                ));
```
Comment (MichaReiser) [inline crates/ruff/src/checkers/noqa.rs:173]: Is my understanding correct that we'll change `#noqa comment` to `# comment`. What's the reasoning behind this choice?

File: crates/ruff/src/checkers/noqa.rs (hunk 1 above)
Comment (MichaReiser) [inline crates/ruff/src/checkers/noqa.rs:164]: Nit: I would find some comments at the top of each case explaining the case they handle and what fix they produce useful.
```suggestion
                            } 
                            // example: `# noqua # another comment`
                            else if lines[row].chars().nth(end + 1).map_or(false, |c| c == '#') {
```

File: crates/ruff/src/checkers/noqa.rs [hunk 3]
```diff
@@ -242,11 +247,20 @@ pub fn check_noqa(
...
+                                {
                                     diagnostic.amend(Fix::deletion(
                                         Location::new(row + 1, start),
                                         Location::new(row + 1, end + trailing_spaces),
                                     ));
+                                } else {
+                                    diagnostic.amend(Fix::deletion(
+                                        Location::new(row + 1, start + 1),
+                                        Location::new(row + 1, end),
+                                    ));
```
Comment (MichaReiser) [inline crates/ruff/src/checkers/noqa.rs:263]: Nit: Is this section a 1:1 copy of the above? Can we extract it in a private-function

File: crates/ruff/src/checkers/noqa.rs [hunk 4]
```diff
@@ -242,11 +247,20 @@ pub fn check_noqa(
                                         Location::new(row + 1, start - leading_spaces),
                                         Location::new(row + 1, end + trailing_spaces),
                                     ));
-                                } else {
+                                } else if lines[row]
+                                    .chars()
+                                    .nth(end + 1)
+                                    .map_or(false, |c| c == '#')
+                                {
```
Comment (MichaReiser) [inline crates/ruff/src/checkers/noqa.rs:254]: Handle extra whitespace between the two comments

**Review by MichaReiser — APPROVED** [review]

File: crates/ruff/src/checkers/noqa.rs (hunk 2 above)
Comment (charliermarsh) [reply crates/ruff/src/checkers/noqa.rs:173]: Yeah this seems wrong -- will change.

File: crates/ruff/src/checkers/noqa.rs (hunk 1 above)
Comment (charliermarsh) [reply crates/ruff/src/checkers/noqa.rs:164]: Will do, added test.

**Comment by charliermarsh** [comment]
Thanks for such a thorough review, I know this is a tricky area.
