### PR TITLE
Remove erroneous method calls in flake8-unused-arguments docs

### LINKED ISSUE #4765: ARG003: Wrong example
The [rule page](https://beta.ruff.rs/docs/rules/unused-class-method-argument/) has an example of correct usage, but it itself contains an error:

```
In [34]: class MyClass:
    ...:     @classmethod
    ...:     def my_method(self, arg1):
    ...:         print(arg1)
    ...:
    ...:     def other_method(self):
    ...:         self.my_method("foo", "bar")
    ...:

In [35]: MyClass().other_method()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[35], line 1
----> 1 MyClass().other_method()

Cell In[34], line 7, in MyClass.other_method(self)
      6 def other_method(self):
----> 7     self.my_method("foo", "bar")

TypeError: MyClass.my_method() takes 2 positional arguments but 3 were given
```

### PR DESCRIPTION
**Pull request by charliermarsh**
Closes #4765.

### CODE REVIEW

File: crates/ruff/src/rules/flake8_unused_arguments/rules/unused_arguments.rs [hunk 1]
```diff
@@ -90,15 +90,15 @@ impl Violation for UnusedFunctionArgument {
 ///
 /// ## Example
 /// ```python
-/// class MyClass:
-///     def my_method(self, arg1, arg2):
+/// class Class:
```
Comment (saippuakauppias) [inline crates/ruff/src/rules/flake8_unused_arguments/rules/unused_arguments.rs:93]: It seems to me that calling the class `Class` is not right, because there are `class` directive
