### PR TITLE
Avoid broken autofix for `SIM103` with `elif`

### LINKED ISSUE #1943: SIM103 fix leaves invalid dangling `else: return False`
```diff
$ ruff --select=SIM103 --diff test.py
--- test.py
+++ test.py
@@ -1,7 +1,6 @@
 def f():
     if 1:
         return 2
-    elif 3 and 4:
-        return True
+    return (3 and 4)
     else:
         return False

Would fix 1 error(s).
```

Ruff forgot to delete the `else:` block, so the resulting code is invalid. Also, the extra parens are unnecessary.

### PR DESCRIPTION
**Pull request by charliermarsh**
Also adjusts the generator to avoid the extra parentheses (and skips commented `if` statements).

Closes #1943.

### CODE REVIEW

File: src/rules/flake8_simplify/rules/ast_if.rs [hunk 1]
```diff
@@ -96,14 +96,16 @@ pub fn return_bool_condition_directly(checker: &mut Checker, stmt: &Stmt) {
...
+        && !(has_comments(stmt, checker.locator) || has_comments(&orelse[0], checker.locator))
+    {
         let return_stmt = create_stmt(StmtKind::Return {
             value: Some(test.clone()),
         });
         diagnostic.amend(Fix::replacement(
             unparse_stmt(&return_stmt, checker.stylist),
             stmt.location,
-            stmt.end_location.unwrap(),
+            orelse[0].end_location.unwrap(),
```
Comment (charliermarsh) [inline src/rules/flake8_simplify/rules/ast_if.rs:108]: If you're in an `elif`, the location on the statement doesn't include the `else`.

Comment (andersk) [reply src/rules/flake8_simplify/rules/ast_if.rs:108]: Yeah, that seems like a bug. Opened RustPython/RustPython#4459.

Comment (charliermarsh) [reply src/rules/flake8_simplify/rules/ast_if.rs:108]: Thanks, much appreciated.
