### PR TITLE
Truncate `SyntaxError`s before newline character

### LINKED ISSUE #3520: Some errors not fit into one line
ruff 0.0.255

When testing files, I see a lot of oneline error info
```
error: Failed to parse Desktop/33/SetPortInfoFF5.py: invalid syntax. Got unexpected token '__init__' at line 13 column 10
error: Failed to parse Desktop/33/PpmImagePlugin4.py: Got unexpected token 󤄳 at line 133 column 35
error: Failed to parse Desktop/33/DTDValidateError4.py: Got unexpected token 𓸾 at line 4 column 1
error: Failed to parse Desktop/33/_test_fortran3.py: unexpected EOF while parsing at line 38 column 1
error: Failed to parse Desktop/33/netr_DELTA_ID_UNION8.py: Got unexpected token 򍾖 at line 14 column 31
error: Failed to parse Desktop/33/winapi7.py: Got unexpected token 􋉐 at line 33 column 1
error: Failed to parse Desktop/33/rtf3.py: invalid syntax. Got unexpected token Newline at line 90 column 45
error: Failed to parse Desktop/33/NETLOGON_SAM_LOGON_RESPONSE6.py: Got unexpected token 񰅣 at line 57 column 65
error: Failed to parse Desktop/33/decoders7.py: Got unexpected nesting at line 2 column 1
error: Failed to parse Desktop/33/comparisons5.py: Got unexpected token 󯻁 at line 1 column 13
error: Failed to parse Desktop/33/abag1.py: unexpected EOF while parsing at line 17 column 1
error: Failed to parse Desktop/33/ed255194.py: invalid syntax. Got unexpected token '|' at line 52 column 2
error: Failed to parse Desktop/33/Content3.py: unexpected EOF while parsing at line 21 column 0
error: Failed to parse Desktop/33/vesti8.py: Got unexpected token 򻲈 at line 3 column 29
error: Failed to parse Desktop/33/libglib-2.0.so.0.7200.3-gdb0.py: Got unexpected token 󵟷 at line 1 column 1
```
but some files produce multiline errors, which is inconsistent and looks bad:
```
error: Failed to parse fix_except0.py: invalid syntax. Got unexpected token """
    try_stmt< 'try' ':' (simple_stmt | suite)
                  cleanup=(except_clause ':' (simple_stmt | suite))+
                  tail=(['except' ':' (simple_stmt | suite)]
                        ['else' ':' (simple_stmt | suite)]
                        ['finally' ':' (simple_stmt | suite)]) >
    """ at line 39 column 14
fix_except0.py:39:15: E999 SyntaxError: invalid syntax. Got unexpected token """
    try_stmt< 'try' ':' (simple_stmt | suite)
                  cleanup=(except_clause ':' (simple_stmt | suite))+
                  tail=(['except' ':' (simple_stmt | suite)]
                        ['else' ':' (simple_stmt | suite)]
                        ['finally' ':' (simple_stmt | suite)]) >
    """
Found 1 error.

```

Example file - [fix_except0.py.zip](https://github.com/charliermarsh/ruff/files/10972513/fix_except0.py.zip)

### PR DESCRIPTION
**Pull request by MichaReiser**
Fixes #3520

**Before**

```
error: Failed to parse  C:\Users\Micha\Downloads\fix_except0.py:39:14: invalid syntax. Got unexpected token """
    try_stmt< 'try' ':' (simple_stmt | suite)
                  cleanup=(except_clause ':' (simple_stmt | suite))+
                  tail=(['except' ':' (simple_stmt | suite)]
                        ['else' ':' (simple_stmt | suite)]
                        ['finally' ':' (simple_stmt | suite)]) >
    """
C:\Users\Micha\Downloads\fix_except0.py:39:14: E999 SyntaxError: invalid syntax. Got unexpected token """
    try_stmt< 'try' ':' (simple_stmt | suite)
                  cleanup=(except_clause ':' (simple_stmt | suite))+
                  tail=(['except' ':' (simple_stmt | suite)]
                        ['else' ':' (simple_stmt | suite)]
                        ['finally' ':' (simple_stmt | suite)]) >
    """
   |
39 |     BM_compatible = True
40 |
41 |     PATTERN  """
   |              ^ E999
42 |     try_stmt< 'try' ':' (simple_stmt | suite)
43 |                   cleanup=(except_clause ':' (simple_stmt | suite))+
   |

Found 1 error.
```

**After**

```
error: Failed to parse C:\Users\Micha\Downloads\fix_except0.py:39:14: unexpected token """⏎...
C:\Users\Micha\Downloads\fix_except0.py:39:14: E999 SyntaxError: unexpected token """⏎...
   |
39 |     BM_compatible = True
40 |
41 |     PATTERN  """
   |              ^ E999
42 |     try_stmt< 'try' ':' (simple_stmt | suite)
43 |                   cleanup=(except_clause ':' (simple_stmt | suite))+
   |

Found 1 error.

```

I decided to implement this in Ruff rather than RustPython becuse this behaviour must only apply in a context where each error should only span a single line. 

Ideally, the parser emit the full range for the token so that we can proberly highlight it in the diagnostic and use the Token text as it appears in the source document (RustPython assumes `"` even if the source text uses `'`). 

## Alternatives

An alternative would be to escape newlines. I decided not to escape newlines because it can lead to extremelly long lines in the output.

### CODE REVIEW

**Comment by MichaReiser** [comment]
Current dependencies on/for this PR:
* main
  * **PR #4124** <a href="https://app.graphite.dev/github/pr/charliermarsh/ruff/4124" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/charliermarsh/ruff/4124?utm_source=stack-comment).

File: crates/ruff/src/logging.rs [hunk 1]
```diff
@@ -150,12 +150,84 @@ impl Display for DisplayParseError<'_> {
...
+
+impl<'a> DisplayParseErrorType<'a> {
+    pub(crate) fn new(error: &'a ParseErrorType) -> Self {
+        Self(error)
+    }
+}
+
+impl Display for DisplayParseErrorType<'_> {
+    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
+        match self.0 {
```
Comment (MichaReiser) [inline crates/ruff/src/logging.rs:173]: I copied this from `RustPython` but wrapped all `tok` variables.

**Review by charliermarsh — APPROVED** [review]
Sorry, I looked at this before, but I felt like I was missing the context and got side-tracked. Does this not have the potential to confuse by way of emitting partial error messages? Why truncate at the first newline>

**Comment by MichaReiser** [comment]
> Sorry, I looked at this before, but I felt like I was missing the context and got side-tracked. Does this not have the potential to confuse by way of emitting partial error messages? Why truncate at the first newline?

It only truncates the token text, not the message itself. I guess, it could be confusing if the unexpected token was a newline, but I think that would already have been confusing today, because Ruff doesn't use special formatting for whitespace.

**Comment by charliermarsh** [comment]
Sounds reasonable -- go for it.
