### PR TITLE
Add a "fix message" to every autofix-able check

### LINKED ISSUE #1454: Add custom messages to the `Fix` API
In LSP extensions, the action prompt is, like, `Fix F401`. We can make these a lot more specific and actionable (e.g., `Remove import Foo`).

### PR DESCRIPTION
**Pull request by charliermarsh**
This PR adds meaningful messages to the `Fix` API.

Prior to this change, the "Quick Fix" actions in VS Code and elsewhere used opaque titles like "Fix F401". Now, they give the user some indication of the _content_ of the fix.

Before:

Screen Shot 2022-12-30 at 10 58 34 PM
Screen Shot 2022-12-30 at 10 58 54 PM

After:

Screen Shot 2022-12-30 at 11 04 32 PM
Screen Shot 2022-12-30 at 10 56 34 PM

Resolves #1454.

### CODE REVIEW

**Comment by charliermarsh** [comment]
I'm now wondering if the fix message should instead be part of the `CheckKind` API, and not a custom thing like this.

**Comment by charliermarsh** [comment]
Screen Shot 2022-12-30 at 6 13 03 PM

File: src/checks.rs [hunk 1]
```diff
@@ -3182,6 +3211,159 @@ impl CheckKind {
...
+            CheckKind::UnnecessaryGeneratorList => None,
+            CheckKind::UnnecessaryGeneratorSet => None,
+            CheckKind::UnnecessaryLRUCacheParams => None,
+            CheckKind::UnnecessaryListCall => None,
+            CheckKind::UnnecessaryListComprehensionDict => None,
+            CheckKind::UnnecessaryListComprehensionSet => None,
+            CheckKind::UnnecessaryLiteralDict(..) => None,
+            CheckKind::UnnecessaryLiteralSet(..) => None,
+            CheckKind::UnnecessaryLiteralWithinListCall(..) => None,
+            CheckKind::UnnecessaryLiteralWithinTupleCall(..) => None,
```
Comment (charliermarsh) [inline src/checks.rs:3350]: Need to finish these, adjust the playground to respect them, then merge.
