### PR TITLE
Flag, but don't fix, unused imports in `ModuleNotFoundError` blocks

### LINKED ISSUE #3378: F401 has started being incorrectly missed
This pattern suddenly has stopped triggering F401:

```python
try:
   import something  # noqa: F401
except ModuleNotFound:
   ...
```

If `something` is never used, the F401 is correct. It's helpful to tell the reader that this is not going to be used later, and it's a hint that this is actually often an incorrect pattern (the correct one in Python 3.4+ is to use `importlib.utils.find_spec("something")`, which won't trigger the error and will be faster, since it doesn't have to run the `Loader`, and won't trigger side effects).

I couldn't find anything in the changelogs or PRs about it, but happened between v0.0.253 and v0.0.254. https://github.com/scikit-hep/hist/pull/482 and https://github.com/pypa/build/pull/585 are two recent cases where this is happening.

### PR DESCRIPTION
**Pull request by charliermarsh**
## Summary

This PR acts on the resolved solution from #3378. In https://github.com/charliermarsh/ruff/pull/3288, we changed Ruff to avoid flagging unused import in `ModuleNotFoundError` blocks, like:

```py
try:
    import orjson

    return True
except ModuleNotFoundError:
    return False
```

This is a common pattern used to detect module availability, and removing those imports tends to break code.

However, these imports _are_ unused, and it's confusing that Ruff doesn't flag them. Further, this isn't the recommended way to test for module availability -- we have `importlib` APIs for that.

So this PR modifies the logic to (1) flag unused imports in blocks like the above, but (2) avoid autofixing them, and (3) using a dedicated message to point the user to those `importlib` APIs.

Closes #3378.

### CODE REVIEW

**Comment by charliermarsh** [comment]
\cc @henryiii

File: crates/ruff/src/rules/pyflakes/rules/imports.rs [hunk 1]
```diff
@@ -13,6 +13,7 @@ use crate::checkers::ast::Checker;
 pub struct UnusedImport {
     pub name: String,
     pub ignore_init: bool,
+    pub in_except_handler: bool,
```
Comment (MichaReiser) [inline crates/ruff/src/rules/pyflakes/rules/imports.rs:16]: Not sure if I'm blind but where do we initialize `in_except_handler`? 

Is it possible for both `ignore_init` and `in_except_handler` to be true? If not, how about we create an enum instead `UnusedImportKind`

**Review by konstin — APPROVED** [review]
i've definitely written that kind that of check and not realized that `importlib.util.find_spec` is a thing

File: crates/ruff/src/checkers/ast/mod.rs [hunk 2]
```diff
@@ -4925,8 +4919,11 @@ impl<'a> Checker<'a> {
                 // Collect all unused imports by location. (Multiple unused imports at the same
                 // location indicates an `import from`.)
                 type UnusedImport<'a> = (&'a str, &'a Range);
-                type BindingContext<'a, 'b> =
-                    (&'a RefEquality<'b, Stmt>, Option<&'a RefEquality<'b, Stmt>>);
+                type BindingContext<'a, 'b> = (
+                    &'a RefEquality<'b, Stmt>,
+                    Option<&'a RefEquality<'b, Stmt>>,
+                    Exceptions,
+                );
```
Comment (MichaReiser) [inline crates/ruff/src/checkers/ast/mod.rs:4926]: Nit: Can we add some documentation about the different tuple fields or maybe it's best to create a struct at this point with named fields to improve readability

**Review by MichaReiser — APPROVED** [review]

File: crates/ruff/src/checkers/ast/mod.rs (hunk 2 above)
Comment (charliermarsh) [reply crates/ruff/src/checkers/ast/mod.rs:4926]: Shoot, this got auto-merged. Yes I'll do a pass on this.
