### PR TITLE
Fix false-positive in RET504 when referencing globals

### LINKED ISSUE #1310: false positive for RET504 in case of globals
The following code results in `RET504 Unnecessary variable assignment before `return` statement`
 
```python
X: int | None = None

def get_x() -> int:
    global X
    if X is None:
        X = 1
    return X
```

however, as it's modifying a global, it's not unnecessary assignment.  (naturally, whether this is a good pattern is a separate discussion :joy: ... but it's not syntactically unnecessary).

(Haven't checked the behavior of flake8-return)

### PR DESCRIPTION
**Pull request by squiddy**
Closes #1310

### CODE REVIEW

File: src/checkers/ast.rs [hunk 1]
```diff
@@ -1269,6 +1257,18 @@ where
...
+                    || self.settings.enabled.contains(&CheckCode::RET502)
+                    || self.settings.enabled.contains(&CheckCode::RET503)
+                    || self.settings.enabled.contains(&CheckCode::RET504)
+                    || self.settings.enabled.contains(&CheckCode::RET505)
+                    || self.settings.enabled.contains(&CheckCode::RET506)
+                    || self.settings.enabled.contains(&CheckCode::RET507)
+                    || self.settings.enabled.contains(&CheckCode::RET508)
+                {
+                    flake8_return::plugins::function(self, body);
+                }
```
Comment (charliermarsh) [inline src/checkers/ast.rs:1270]: Could we pass in the list of globals, rather than relying on current_scope? That would remove the implicit dependence on the state of the scope stack when this is called.

Comment (squiddy) [reply src/checkers/ast.rs:1270]: I was thinking of just passing `&globals` here, but I'm having some borrow-checker issues, because the globals are moved into the new scope which is taken by `push_scope`.

That said, I was just thinking that this example should also not trigger a `RET504`.

```python
def nonlocal_assignment():
    X = 1
    def inner():
        nonlocal X
        X = 1
        return X
```

So I'm wondering whether I even need to look into globals for this. Need to check the code.

Comment (squiddy) [reply src/checkers/ast.rs]: Have taken a different approach now.
